// ─── Pebble Beach Golf Links — Course Data ───
// Real hole descriptions, yardage, par, and scenery

const COURSE_DATA = {
  name: 'Pebble Beach Golf Links',
  location: 'Pebble Beach, California',
  established: 1919,

  holes: [
    {
      number: 1,
      par: 4,
      yards: 381,
      name: 'The Opening',
      teeDescription: `The morning mist hasn't quite burned off yet. You stand on the first tee of Pebble Beach, the most famous opening hole in American golf. A slight dogleg right, the fairway climbs gently uphill, lined by Monterey pines whose branches have been sculpted by decades of Pacific wind. The green sits elevated above you, tucked behind a pair of bunkers. The clubhouse is just behind you — you can still smell the coffee from the restaurant. A few early spectators lean against the fence. This is it.`,
      approachDescription: `Your ball sits in the fairway with a clean lie. The green is uphill, protected by two front bunkers that catch anything short. The pin is back-left today, near the edge where the green slopes off sharply. A light breeze pushes across from the ocean, though you can't see the water yet — that comes later. You can feel the texture of the fairway under your spikes. Firm, fast, well-maintained. The kind of turf that rewards a clean strike.`,
      puttDescription: `You're on the green now. The surface is immaculate — a blend of Poa annua typical of Pebble Beach, slightly grainy, reading faster than it looks. Your ball sits {distance} from the cup. The break is subtle but there — everything feeds slightly toward the ocean here, even when you can't see it.`,
    },
    {
      number: 2,
      par: 5,
      yards: 502,
      name: 'The Climb',
      teeDescription: `Hole two. A par 5 that doglegs sharply right and climbs uphill. From the tee, you stare down a wide fairway, but the real challenge is the second shot — the hole bends right and rises steeply toward a green that sits on a plateau. Monterey pines crowd both sides. The smart play is left-center off the tee, leaving a long second shot up the hill. But if you bomb one, you can cut the corner and get home in two. The Pacific is starting to appear through the trees to your right. Just glimpses for now.`,
      approachDescription: `You're somewhere up the fairway, staring at a steep uphill approach. The green sits on a shelf above you, partially hidden. What you can see: the flag fluttering in the wind that's picked up since the first hole, and two deep bunkers flanking the front. The elevation change adds at least a club. Maybe a club and a half. Getting this distance right is the whole game here.`,
      puttDescription: `The elevated green is surprisingly flat for Pebble Beach, but don't be fooled — there's a subtle tier in the middle. You're {distance} out. Your read says this breaks {break_direction}, but the grain runs the opposite way. This is where local knowledge separates the tourists from the regulars.`,
    },
    {
      number: 3,
      par: 4,
      yards: 390,
      name: 'Ocean's Edge',
      teeDescription: `Here's where Pebble Beach starts to show you what it really is. Hole three swings left along the cliff's edge, and for the first time you are standing directly above the Pacific. The waves are crashing against the rocks maybe eighty feet below. Stillwater Cove opens up to your left — boats bobbing, seals sunning on the rocks. The fairway tilts left toward the ocean. A pushed tee shot finds the Pacific. A pulled one finds the trees. The landing area is generous if you pick the right line. The wind is directly in your face now.`,
      approachDescription: `The approach shot on three is all about club selection. The green sits perched above the cove, slightly elevated, with a false front that will reject anything that doesn't commit. The ocean is directly behind the green. If you fly it long, your ball is swimming. The wind is swirling off the water — it was in your face a moment ago, now it seems to have died. Or shifted. Hard to tell. Your caddie, if you had one, would tell you to trust the wind at the top of the flag, not at your feet.`,
      puttDescription: `Ocean-side green. You can hear the waves below while you read this putt. {distance} to the cup. The green slopes toward the cliff — everything breaks toward the water. Your playing partner Dave is watching. He three-putted this green last time and hasn't shut up about it.`,
    },
    {
      number: 4,
      par: 4,
      yards: 327,
      name: 'The Beach Hole',
      teeDescription: `Number four. Only 327 yards, which at Pebble Beach means it's trying to trick you. The hole plays downhill along the coastline, the entire Pacific panorama spread out to your left. The fairway is narrow, squeezed between ocean cliff and a row of ancient cypress trees on the right. A massive bunker guards the left side of the green. The temptation is to take driver and go for the green — it's reachable. But the consequences of missing are career-ending. The smart play is a long iron to the center of the fairway, leaving a pitch to a small, sloping green. What's it going to be?`,
      approachDescription: `A short pitch from the fairway. The green is small, angled toward the ocean, with that gaping bunker on the left. The pin is cut close to the edge today — a sucker pin, daring you to go at it. The safe play is center-green and take your two putts. But you didn't fly across the country to play it safe at Pebble Beach. Or did you?`,
      puttDescription: `Small green, big slopes. This thing is like a tabletop tilted toward the sea. You're {distance} away and you can practically see the break with your eyes closed. Dave just hit a beautiful lag putt to about two feet. He's looking at you now, waiting. No pressure.`,
    },
    {
      number: 5,
      par: 3,
      yards: 188,
      name: 'The Cliff',
      teeDescription: `The fifth at Pebble Beach. A par 3, 188 yards, but every one of those yards is over a chasm. The tee sits on one promontory, the green on another, with the ocean churning in the gap between them. There is no bailout. There is no layup. There is only the green, and everything else is rocks, waves, and regret. The wind is quartering into you from the left. Three seagulls ride the updraft off the cliff face, completely unconcerned with your existential crisis. Your hands might be sweating. That's normal here.`,
      approachDescription: null,
      puttDescription: `You're on the green at the famous fifth. The putting surface undulates gently, with a ridge running through the center that can make a four-footer feel like twenty. You're {distance} from the pin. The ocean roars below. Somewhere behind you, a tourist is taking a photo. Dave is already marking his ball, looking relaxed. He stuck it to six feet. Of course he did.`,
    },
    {
      number: 6,
      par: 5,
      yards: 513,
      name: 'Stillwater',
      teeDescription: `Hole six. A par 5 that plays uphill and away from the ocean, back toward the interior of the property. After the drama of four and five, this one feels like a deep breath. The fairway is wide, the trees are tall, and the atmosphere shifts from adrenaline to strategy. A creek crosses the fairway about 80 yards from the green — it doesn't look like much, but it's caught plenty of second shots from players trying to reach in two. The green is elevated and well-bunkered. The smart play is three good shots. The exciting play is to bomb two and hope.`,
      approachDescription: `You're somewhere up the fairway, the creek between you and the green. If you lay up short of the water, you'll have a comfortable wedge in. If you go for it, you need to carry {carry_distance} yards over the creek and hold a firm green. The risk-reward calculation is screaming at you from both sides. What does your gut say?`,
      puttDescription: `A generous green with some movement. You're putting from {distance}. The surface is a bit slower here — more shade from the surrounding pines keeps it damp longer in the morning. A firm stroke needed. Dave is telling a story about the time he lost three balls in the creek. You're trying to listen and read your line at the same time.`,
    },
    {
      number: 7,
      par: 3,
      yards: 106,
      name: 'The Postcard',
      teeDescription: `Hole seven. One hundred and six yards. The shortest hole at Pebble Beach, and arguably the most photographed hole in golf. The tiny green sits on a rocky point jutting out into Carmel Bay, completely exposed to the elements. The ocean wraps around three sides. On a calm day, it's a gentle wedge to a benign target. Today is not a calm day. The wind is howling off the bay, the flag is horizontal, and the green — which is the size of a living room — is surrounded by bunkers, rocks, and the Pacific Ocean. Jack Nicklaus hit a 1-iron here once. It was 1972 and the wind was blowing sideways. You're holding a sand wedge and your confidence.`,
      approachDescription: null,
      puttDescription: `The tiniest green on the course, maybe on any major championship course. You're {distance} from the hole. The wind is still pushing. Your ball didn't even seem to settle — it just stopped, as if the green grabbed it. The surface is firm and fast, with the grain running toward the bay. Dave is shaking his head, either in admiration or pity. You're not sure which.`,
    },
    {
      number: 8,
      par: 4,
      yards: 428,
      name: 'The Cliffhanger',
      teeDescription: `Eight at Pebble Beach. This is the one. The signature hole. A par 4 that requires a blind tee shot across a gaping inlet of the Pacific Ocean. You stand on the tee and look at nothing but cliff, water, and sky. The fairway is up there somewhere, 200 yards across the chasm, but you can't see it. You just aim at the right edge of the tree line on the far cliff and swing. If you've never hit this shot, nothing prepares you for it. The sound of the ocean is everywhere. The drop is maybe a hundred feet. Your playing partner Dave hit first and absolutely pured it. You watched it soar across the void and land safely on the other side. Now it's your turn. The ocean doesn't care about your handicap.`,
      approachDescription: `You made it across. Standing in the fairway on the far side of the chasm, the approach to eight is a long one — the green is elevated and guarded by bunkers. The second shot here is almost as famous as the tee shot: a long iron or hybrid, uphill, to a green that slopes severely from back to front. Anything long rolls off the back into trouble. Anything short feeds back down the false front to the fairway. You need to land it on the green and have it stop. Surgical precision from {approach_distance} yards.`,
      puttDescription: `The green on eight slopes dramatically from back to front. If you're above the hole, pray. You're {distance} from the cup, and the speed is everything. Too firm and you're putting again from where you started. Not firm enough and gravity pulls it back to your feet. This green has broken hearts in every US Open ever played here. Dave is already done — he two-putted and is sitting on the cart looking at the ocean.`,
    },
    {
      number: 9,
      par: 4,
      yards: 466,
      name: 'The Turn',
      teeDescription: `The ninth. Last hole of the front nine. 466 yards, the longest par 4 on the course, playing directly along the cliff edge. The Pacific is on your left, an unbroken wall of ocean stretching to the horizon. The fairway runs parallel to the coast, narrow and exposed, with the cliff face dropping away just yards from the left rough. A stand of Monterey pines guards the right side. The wind is behind you for once, which sounds helpful until you realize it makes the ball harder to stop on the green. This is a brute. A beautiful, oceanside, wind-swept brute. The turn feels earned here — if you're still standing after nine holes at Pebble Beach, you've been somewhere.`,
      approachDescription: `Long approach into the ninth green. The green is long and narrow, running parallel to the cliff. Two bunkers on the left, ocean beyond them. The pin is in the center today — a fair position on an unfair hole. You've got {approach_distance} yards in, the wind at your back, and you're trying to calculate how much it'll help. One club less? Two? The cliff is right there, close enough to hear individual waves hitting the rocks.`,
      puttDescription: `The ninth green. Last putt of the front nine. {distance} to go. The green is firm and fast, leaning toward the ocean like everything else out here. This putt means something — it's the one that sets the tone for whatever comes next. Dave is being uncharacteristically quiet. Maybe he knows. Or maybe he's just looking at the view. From here, you can see all the way down the coast, past Carmel, past Point Lobos, to where the horizon dissolves into mist.`,
    },
  ],
};
