// ─── Fujo International Golf Club — Course Data ───

const COURSE_DATA = {
  name: 'Fujo International Golf Club',
  location: 'Hakone, Japan',
  established: 1987,

  holes: [
    {
      number: 1,
      par: 4,
      yards: 375,
      name: 'The Arrival',
      teeDescription: `Cherry blossoms line the fairway. Mist on the ridge. Martin is already aligned. Sato watches the mist move.`,
      approachDescription: `Clean lie. Green rises behind shallow bunkers. Pin back-left, where greed gets punished.`,
      puttDescription: `{distance} from the cup. Breaks toward the valley, {break_direction}.`,
    },
    {
      number: 2,
      par: 5,
      yards: 510,
      name: 'Kaminari',
      teeDescription: `The hole drops through bamboo, then climbs. A par 5 built on elevation. Stone guardians line the bend. Sato hasn't spoken since the car.`,
      approachDescription: `Green sits on a shelf above you. Bunkers cut into the hillside. One more club than the number says.`,
      puttDescription: `Tiered green. {distance} out, breaks {break_direction}. The grain disagrees.`,
    },
    {
      number: 3,
      par: 4,
      yards: 395,
      name: 'The Bridge',
      teeDescription: `Stone bridge over a koi stream. Moss-slick, ancient. Your ball has to clear it or negotiate it. Claire texts: Let me know if he asks about the deck.`,
      approachDescription: `Green past the stream's bend, slightly elevated. False front rejects timid shots.`,
      puttDescription: `Stream-side green. {distance} to the cup, {break_direction}. You can hear the water.`,
    },
    {
      number: 4,
      par: 4,
      yards: 335,
      name: 'Sakura Bend',
      teeDescription: `Short. Dogleg through cherry trees. The fairway looks generous until you notice how the shadows lie. Martin pulls a long iron. Predictable. Correct.`,
      approachDescription: `Short iron to a shallow green. Bunker grins at aggressive lines. Pin cut tight.`,
      puttDescription: `Small green. {distance}, {break_direction}. Martin just two-putted without expression.`,
    },
    {
      number: 5,
      par: 3,
      yards: 185,
      name: 'The Gorge',
      teeDescription: `185 yards over a volcanic gorge. Mist. Black rock. No bailout. Martin tees up, face blank. Sato reads the wind. Claire knows not to text on this tee.`,
      approachDescription: null,
      puttDescription: `You made the carry. {distance} from the pin, {break_direction}. The gorge exhales below.`,
    },
    {
      number: 6,
      par: 5,
      yards: 520,
      name: 'Stillwater',
      teeDescription: `Par 5 along a mirror lake. The reflection is too real. Fairway bends left along the shore. Fish rise in slow rings. Martin counts steps.`,
      approachDescription: `Water beside you. Stream crosses short of the green. Lay up for a wedge, or carry {carry_distance} and hold.`,
      puttDescription: `Generous green. {distance}, {break_direction}. Grass slower here — moisture off the lake.`,
    },
    {
      number: 7,
      par: 3,
      yards: 110,
      name: 'The Lantern',
      teeDescription: `110 yards. Stone lanterns surround the green, worn smooth by centuries. Bunkers pinch like ink strokes. Wind moves differently here.`,
      approachDescription: null,
      puttDescription: `Smallest green on the course. {distance}, {break_direction}. Firm and quick.`,
    },
    {
      number: 8,
      par: 4,
      yards: 435,
      name: 'The Ridge',
      teeDescription: `Ridgeline hole. Fairway ribbon-thin, slopes falling both sides. Sky wide open. Wind wants to help and hurt at once.`,
      approachDescription: `{approach_distance} yards to a green perched like an altar. Anything long is mountain. Anything short is work.`,
      puttDescription: `{distance}, {break_direction}. Severe above the hole, kind below. Speed is the whole sermon.`,
    },
    {
      number: 9,
      par: 4,
      yards: 460,
      name: 'The Return',
      teeDescription: `Last hole. 460 yards downhill toward the clubhouse. Mountains open behind you in layers of blue. Martin walks ahead, on schedule. Claire can wait.`,
      approachDescription: `Long approach. Pin middle — fair, which somehow feels cruel. {approach_distance} yards in, breeze helping.`,
      puttDescription: `Last putt. {distance}, {break_direction}. Quick turf, afternoon sun. The temple bell sounds once.`,
    },
  ],
};
