const DATA = {

  kidsJokes: [
    { setup: "What do you call a bear with no teeth?", punch: "A gummy bear." },
    { setup: "Why did the bicycle fall over?", punch: "It was two-tired." },
    { setup: "What's brown and sticky?", punch: "A stick." },
    { setup: "What did the buffalo say when his kid left for college?", punch: "Bison." },
    { setup: "Why can't you trust atoms?", punch: "They make up everything." },
    { setup: "What do you call a fake noodle?", punch: "An impasta." },
    { setup: "Why don't skeletons fight each other?", punch: "They don't have the guts." },
    { setup: "What did the ocean say to the beach?", punch: "Nothing. It just waved." },
    { setup: "Why did the math book look sad?", punch: "Too many problems." },
    { setup: "What do you call cheese that isn't yours?", punch: "Nacho cheese." },
    { setup: "Why do seagulls fly over the sea?", punch: "Because if they flew over the bay they'd be bagels." },
    { setup: "What do you call a sleeping dinosaur?", punch: "A dino-snore." },
    { setup: "What has ears but can't hear?", punch: "A cornfield." },
    { setup: "Why can't Elsa hold a balloon?", punch: "Because she'll let it go." },
    { setup: "What do you call a dog that does magic?", punch: "A Labracadabrador." },
    { setup: "How do you organize a space party?", punch: "You planet." },
    { setup: "What did one wall say to the other?", punch: "I'll meet you at the corner." },
    { setup: "Why did the golfer bring two pairs of pants?", punch: "In case he got a hole in one." },
    { setup: "What do you call a fish without eyes?", punch: "A fsh." },
    { setup: "What do elves learn in school?", punch: "The elf-abet." },
    { setup: "Why did the teddy bear say no to dessert?", punch: "She was already stuffed." },
    { setup: "What do you give a sick lemon?", punch: "Lemon aid." },
    { setup: "Why are ghosts bad liars?", punch: "You can see right through them." },
    { setup: "What did the left eye say to the right eye?", punch: "Between us, something smells." },
    { setup: "Why don't elephants use computers?", punch: "They're afraid of the mouse." },
    { setup: "What has four wheels and flies?", punch: "A garbage truck." },
    { setup: "What do you call a boomerang that won't come back?", punch: "A stick." },
    { setup: "Why did the banana go to the doctor?", punch: "It wasn't peeling well." },
    { setup: "What do snowmen eat for breakfast?", punch: "Frosted flakes." },
    { setup: "How do you make an octopus laugh?", punch: "With ten-tickles." },
    { setup: "Why was the broom late?", punch: "It over-swept." },
    { setup: "What's a cat's favorite color?", punch: "Purrr-ple." },
    { setup: "Why couldn't the pony sing?", punch: "It was a little horse." },
    { setup: "What do you call a pig that does karate?", punch: "A pork chop." },
    { setup: "Why did the cookie go to the hospital?", punch: "It felt crummy." },
  ],

  adultJokes: [
    { setup: "The early bird gets the worm.", punch: "But the second mouse gets the cheese." },
    { setup: "I told my wife she was drawing her eyebrows too high.", punch: "She looked surprised." },
    { setup: "I broke up with my gym.", punch: "We just weren't working out." },
    { setup: "Parallel lines have so much in common.", punch: "It's a shame they'll never meet." },
    { setup: "I stayed up all night wondering where the sun went.", punch: "Then it dawned on me." },
    { setup: "I tried to catch fog yesterday.", punch: "Mist." },
    { setup: "What do you call a magician who lost his magic?", punch: "Ian." },
    { setup: "I'm reading a book about anti-gravity.", punch: "It's impossible to put down." },
    { setup: "A man walks into a library and asks for books about paranoia.", punch: "The librarian whispers, 'They're right behind you.'" },
    { setup: "My therapist says I have a preoccupation with vengeance.", punch: "We'll see about that." },
    { setup: "I have a fear of speed bumps.", punch: "But I'm slowly getting over it." },
    { setup: "I used to hate facial hair.", punch: "But then it grew on me." },
    { setup: "A man tells his doctor, 'I broke my arm in two places.'", punch: "The doctor says, 'Stop going to those places.'" },
    { setup: "I told my suitcases we aren't going on vacation this year.", punch: "Now I'm dealing with emotional baggage." },
    { setup: "Why do Norwegian boats have barcodes on the side?", punch: "So when they come into port, they can Scandinavian." },
    { setup: "My wife told me to stop impersonating a flamingo.", punch: "I had to put my foot down." },
    { setup: "I just found out I'm colorblind.", punch: "The news came completely out of the purple." },
    { setup: "I asked the IT guy, 'How do you make a motherboard?'", punch: "'Tell her about my job.'" },
    { setup: "What's the best thing about Switzerland?", punch: "I don't know, but the flag is a big plus." },
    { setup: "I wasn't originally going to get a brain transplant.", punch: "But then I changed my mind." },
    { setup: "What's the difference between a hippo and a Zippo?", punch: "One is really heavy, the other is a little lighter." },
    { setup: "My wife asked me to stop singing Wonderwall.", punch: "I said maybe." },
    { setup: "I just burned 2,000 calories.", punch: "That's the last time I leave brownies in the oven." },
    { setup: "I told my friend she drew her eyebrows too high.", punch: "She seemed surprised." },
    { setup: "Did you hear about the claustrophobic astronaut?", punch: "He just needed a little space." },
    { setup: "I'm friends with 25 letters of the alphabet.", punch: "I don't know Y." },
    { setup: "I used to be addicted to soap.", punch: "But I'm clean now." },
    { setup: "My doctor told me I'm going deaf.", punch: "The news was hard for me to hear." },
    { setup: "I don't trust stairs.", punch: "They're always up to something." },
    { setup: "A plateau is the highest form of flattery.", punch: "" },
    { setup: "I told my wife she was overreacting.", punch: "She just rolled her eyes and left. The audacity." },
    { setup: "What do dentists call their x-rays?", punch: "Tooth pics." },
    { setup: "My boss told me to have a good day.", punch: "So I went home." },
    { setup: "I can't believe I got fired from the calendar factory.", punch: "All I did was take a day off." },
    { setup: "What sits at the bottom of the sea and twitches?", punch: "A nervous wreck." },
  ],

  starters: [
    "What three songs would make the soundtrack of your year?",
    "What's something you changed your mind about recently?",
    "What's the best meal you've had this month?",
    "If you could live in any decade, which would you pick?",
    "What's a skill you'd love to learn but haven't started?",
    "What's the worst haircut you've ever had?",
    "What would you do if you won the lottery tomorrow?",
    "What's a movie you can watch over and over?",
    "If you could have dinner with anyone, alive or dead, who?",
    "What's something most people don't know about you?",
    "What's your go-to comfort food?",
    "What's the best trip you've ever taken?",
    "What were you like in high school?",
    "What's something you're weirdly good at?",
    "If you could wake up tomorrow with one new ability, what?",
    "What's a hill you'll die on?",
    "What's the most interesting thing you've read lately?",
    "What's a conspiracy theory you kind of believe?",
    "What show are you bingeing right now?",
    "What's the weirdest food combination you actually enjoy?",
    "If your life had a theme song, what would it be?",
    "What's something that's on your bucket list?",
    "What's the nicest thing a stranger ever did for you?",
    "If you could relive one day of your life, which?",
    "What's a hobby you picked up during COVID that stuck?",
  ],

  wouldYouRather: [
    ["Be able to fly", "Be able to read minds"],
    ["Always be 10 minutes late", "Always be 20 minutes early"],
    ["Live without music", "Live without movies"],
    ["Have unlimited money", "Unlimited time"],
    ["Know how you die", "Know when you die"],
    ["Be famous but misunderstood", "Unknown but deeply fulfilled"],
    ["Only eat one food forever", "Never eat your favorite food again"],
    ["Travel 100 years into the future", "100 years into the past"],
    ["Be the funniest person in the room", "The smartest"],
    ["Have a rewind button", "A pause button for life"],
    ["Give up your phone", "Give up your bed"],
    ["Always speak your mind", "Never speak again"],
    ["Live in the mountains", "Live on the beach"],
    ["Be a famous actor", "A famous musician"],
    ["Know every language", "Play every instrument"],
    ["Always be slightly cold", "Always be slightly hot"],
    ["Have free Wi-Fi everywhere", "Free coffee everywhere"],
    ["Win a Grammy", "Win an Olympic gold"],
    ["Never have to sleep", "Never have to eat"],
    ["Relive your childhood", "Fast-forward to retirement"],
  ],

  iceBreakers: [
    "Two truths and a lie — everyone shares three things, group guesses which is false.",
    "If you were a sandwich, what sandwich would you be and why?",
    "What's the most useless talent you have? Demonstrate it.",
    "Everyone shows the last photo in their camera roll and explains it.",
    "In one word, describe your week. Then explain.",
    "What's the worst date you've ever been on?",
    "If you had to be haunted by a ghost, which celebrity would you choose?",
    "What's your most unpopular opinion?",
    "Show the group your most-used emoji. Explain yourself.",
    "If your pet could talk, what would it say about you?",
    "What's the dumbest way you've ever injured yourself?",
    "What song do you secretly know every word to?",
    "Describe your job to us like you're explaining it to a five-year-old.",
    "What's your toxic trait?",
    "If you had a warning label, what would it say?",
  ],

  toasts: [
    "Here's to the nights we'll never remember with the people we'll never forget.",
    "May your glass be ever full, may the roof over your head be always strong, and may you be in heaven half an hour before the devil knows you're dead.",
    "To good friends, good times, and poor decisions.",
    "Here's to being single, seeing double, and sleeping triple.",
    "May we be who our dogs think we are.",
    "Here's to the ones who wish us well. All the rest can go to hell.",
    "To alcohol — the cause of, and solution to, all of life's problems.",
    "May your troubles be less, your blessings be more, and nothing but happiness come through your door.",
    "Here's to staying positive and testing negative.",
    "In the words of my father: don't be an idiot. It changed my life.",
  ],
};

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
