// ─── Editor Data Model ───
// All story content in a flat, editor-friendly JSON structure.
// The editor reads/writes this. Export converts it to game-compatible JS.

const EDITOR_DATA = {
  meta: {
    title: 'Corporate Golf',
    subtitle: 'The Anderson Account — Season 1',
    version: '0.1.0',
    lastEdited: null,
  },

  npcs: {
    dave: {
      id: 'dave',
      name: 'Dave Kowalski',
      role: 'Senior Associate, Business Development',
      personality: 'Friendly, self-deprecating, competitive underneath. Genuinely decent.',
      secret: 'Been passed over twice for the Anderson lead. This is his last shot before he looks elsewhere.',
      statKey: 'impression',
      icon: '👔',
      lineCount: 0,
    },
    sharon: {
      id: 'sharon',
      name: 'Sharon Whitfield',
      role: 'VP of Client Services',
      personality: 'Sharp, strategic, uses corporate-speak as a weapon. Not evil — just playing a different game.',
      secret: 'Leaving Meridian in 3 months. Needs Anderson locked down as her legacy.',
      statKey: null,
      icon: '📱',
      lineCount: 0,
    },
    tom: {
      id: 'tom',
      name: 'Tom Anderson',
      role: 'CEO, Anderson Industrial',
      personality: 'Old money charm, plays dumb but misses nothing.',
      secret: 'Already talking to a competitor. This golf outing is partly a goodbye tour.',
      statKey: null,
      icon: '🏌️',
      lineCount: 0,
    },
    narrator: {
      id: 'narrator',
      name: 'Narrator',
      role: 'Narrative voice',
      personality: 'Calm, literary, wry. Intimate, not booming.',
      secret: null,
      statKey: null,
      icon: '📖',
      lineCount: 0,
    },
  },

  flags: [
    { id: 'admitted_nerves', setBy: 'dialogue_h1', readBy: ['dialogue_h2', 'dialogue_h3'], description: 'Player admitted to being nervous on hole 1' },
    { id: 'cooperating_with_sharon', setBy: 'phone_h3', readBy: ['dialogue_h4', 'phone_h5', 'phone_h7', 'ending'], description: 'Player is feeding Sharon info about Dave' },
    { id: 'deflected_sharon', setBy: 'phone_h3', readBy: ['phone_h5'], description: 'Player deflected Sharon\'s first text' },
    { id: 'left_sharon_on_read', setBy: 'phone_h3', readBy: ['phone_h5', 'ending'], description: 'Player ignored Sharon\'s text entirely' },
    { id: 'told_dave_about_anderson', setBy: 'dialogue_h4', readBy: ['dialogue_h6', 'dialogue_h8', 'ending'], description: 'Player told Dave about the Anderson Account situation' },
    { id: 'dave_shared_struggle', setBy: 'walking_h6', readBy: ['dialogue_h7', 'thought_h8', 'ending'], description: 'Dave opened up about being passed over' },
    { id: 'empathized_with_dave', setBy: 'walking_h6', readBy: ['dialogue_h8', 'ending'], description: 'Player showed empathy when Dave opened up' },
    { id: 'warned_dave_about_sharon', setBy: 'dialogue_h7', readBy: ['dialogue_h8', 'ending'], description: 'Player warned Dave that Sharon is evaluating him' },
    { id: 'accepted_sharon_deal', setBy: 'phone_h7', readBy: ['thought_h8', 'ending'], description: 'Player committed to Sharon for Anderson lead' },
    { id: 'rejected_sharon_deal', setBy: 'phone_h7', readBy: ['ending'], description: 'Player let Sharon\'s call go to voicemail' },
    { id: 'bet_with_dave', setBy: 'dialogue_h3', readBy: ['ending'], description: 'Player made a lunch bet with Dave' },
    { id: 'chose_dave', setBy: 'dialogue_h8', readBy: ['ending'], description: 'Player chose loyalty to Dave over career advancement' },
    { id: 'chose_career', setBy: 'dialogue_h8', readBy: ['ending'], description: 'Player chose career over loyalty to Dave' },
  ],

  holes: [
    {
      number: 1,
      name: 'First Impressions',
      par: 4,
      yards: 381,
      theme: 'Establishment — who are you?',
      arcBeat: 'Meeting Dave. Light small talk. Seeds planted about the corporate context.',
      beats: {
        intro: {
          id: 'intro_h1',
          text: 'The morning mist hasn\'t quite burned off yet. You stand on the first tee of Pebble Beach. Slight dogleg right, 381 yards. The fairway is generous — a forgiving opening. To your right, the practice green. Behind you, the clubhouse where your boss Sharon waved you off with a smile that had too many teeth.',
          status: 'written',
        },
        tee_thoughts: [
          {
            id: 'thought_h1_tech',
            label: 'SWING THOUGHT',
            text: 'Focus on keeping your lead shoulder under your chin and completing the full turn. Trust the swing path you grooved on the range.',
            baseQuality: 1,
            traitEffects: { focus: 5, knowledge: 3 },
            resultGood: 'Clean contact. The ball flies straight, maybe a slight draw, landing center fairway.',
            resultBad: 'Solid thought, but you got quick at the top. The ball leaks right. Playable.',
            status: 'written',
          },
          {
            id: 'thought_h1_dad',
            label: 'DAD WISDOM',
            text: '"Swing easy, hit hard." That\'s what your old man always said.',
            baseQuality: 2,
            traitEffects: { zen: 4, swagger: 2 },
            resultGood: 'Easy does it. The ball floats down the fairway with effortless trajectory.',
            resultBad: 'You swung so easy you forgot to actually swing. Caught it thin.',
            status: 'written',
          },
          {
            id: 'thought_h1_distract',
            label: 'DISTRACTION',
            text: 'Sharon\'s smile at the clubhouse. What was that about? She never smiles like that. Is this an evaluation?',
            baseQuality: 4,
            traitEffects: { focus: -6, knowledge: 2 },
            resultGood: 'Despite the distraction, your body knows what to do. Middle of the fairway.',
            resultBad: 'The corporate anxiety locks your shoulders. You come over the top. Left rough.',
            status: 'written',
          },
          {
            id: 'thought_h1_send',
            label: 'SEND IT',
            text: 'Pebble Beach. First tee. You might never be back. Grip it and rip it.',
            baseQuality: 3,
            traitEffects: { swagger: 6, focus: -3 },
            resultGood: 'You absolutely unload on it. Dave\'s jaw drops.',
            resultBad: 'You try to muscle it and everything breaks down. Trees, left.',
            status: 'written',
          },
        ],
        walking_1: {
          id: 'walk_h1_after_tee',
          text: 'You and Dave walk off the first tee together. The fairway stretches ahead. He pulls a granola bar from his bag without asking if you want one.',
          choices: [
            { label: 'ACCEPT', text: '"Thanks. Peanut butter?"', traitEffects: { humor: 2 }, partnerEffect: { impression: 3 }, setFlags: {} },
            { label: 'DECLINE', text: '"I\'m good, thanks."', traitEffects: { focus: 2 }, partnerEffect: {}, setFlags: {} },
          ],
          status: 'written',
        },
        approach_thoughts: [
          {
            id: 'thought_h1_approach_viz',
            label: 'VISUALIZATION',
            text: 'Visualize the trajectory — high, soft, lands and checks.',
            baseQuality: 1,
            traitEffects: { focus: 4, knowledge: 3 },
            resultGood: 'The ball does exactly what you saw in your mind.',
            resultBad: 'You saw it perfectly. Your body had other plans.',
            status: 'written',
          },
        ],
        putt_thoughts: [
          {
            id: 'thought_h1_putt_spot',
            label: 'SPOT PUTTING',
            text: 'Pick a spot two feet in front of the ball. Roll it over that spot.',
            baseQuality: 1,
            traitEffects: { focus: 4, knowledge: 4 },
            resultGood: 'Over the spot, down the line, into the cup.',
            resultBad: 'Over the spot and past the hole. Pace was off.',
            status: 'written',
          },
        ],
        dialogue_tree: {
          id: 'dialogue_h1',
          nodes: [
            {
              id: 'start',
              speaker: 'narrator',
              text: 'You and Dave walk off the first green toward the second tee. The mist is lifting.',
              next: 'dave_opener',
              responses: [],
            },
            {
              id: 'dave_opener',
              speaker: 'dave',
              text: '[DYNAMIC] Based on score: if good → "Not a bad start..." if bad → "Shake it off..."',
              dynamicNote: 'References state.scorecard[0] vs par',
              next: null,
              responses: [
                {
                  id: 'r_honest',
                  label: 'HONEST',
                  text: '"Calm? My hands were shaking the entire time."',
                  statKey: 'swagger',
                  receivedVariants: {
                    1: 'You stammer about your hands. Dave looks concerned.',
                    2: '"My h-hands were, um, shaking." It comes out weird.',
                    3: '"My hands were shaking." Dave nods.',
                    4: '"Calm? Please. My hands were shaking the entire time. I just have a good poker face." Delivered with charm.',
                    5: '"Calm? My hands were shaking so hard I thought I was going to launch the ball backwards." Dave roars with laughter. Instant connection.',
                  },
                  traitEffects: { humor: 4, zen: -2 },
                  partnerEffect: { impression: 6 },
                  setFlags: { admitted_nerves: true },
                  next: 'dave_laughs',
                },
                {
                  id: 'r_confident',
                  label: 'CONFIDENT',
                  text: '"I visualized this round last night. Every shot."',
                  statKey: 'swagger',
                  receivedVariants: {
                    1: '"I vis... visualized it." You can\'t finish the sentence. Dave stares.',
                    2: '"I visualized it!" Too enthusiastic. Dave raises an eyebrow.',
                    3: '"I visualized this round last night." Dave nods, neither impressed nor unimpressed.',
                    4: '"I visualized every shot last night. This first hole played out exactly how I saw it." Dave is intrigued.',
                    5: '"I played this round in my head at 2 AM. Every lie, every read. What I saw was better than what happened — but we\'re getting there." Dave looks at you differently now.',
                  },
                  traitEffects: { swagger: 4, focus: 2 },
                  partnerEffect: { impression: 3 },
                  setFlags: {},
                  next: 'dave_eyebrow',
                },
                {
                  id: 'r_deflect',
                  label: 'DEFLECT',
                  text: '"I\'m just glad I didn\'t whiff it in front of the clubhouse."',
                  statKey: 'humor',
                  receivedVariants: {
                    1: 'A failed attempt at humor. The silence is deafening.',
                    2: '"I\'m just glad I didn\'t, uh, whiff it." Not quite a joke. Not quite anything.',
                    3: '"Just glad I didn\'t whiff it." Dave smiles politely.',
                    4: '"I\'m just glad I didn\'t whiff it in front of the entire clubhouse patio. Sharon would\'ve revoked my badge." Dave chuckles.',
                    5: '"I\'m just glad I made contact. My last round, I whiffed so hard on the first tee that my playing partner asked if I was okay. Like, medically." Dave is howling.',
                  },
                  traitEffects: { humor: 5, focus: -1 },
                  partnerEffect: { impression: 4 },
                  setFlags: {},
                  next: 'dave_chuckles',
                },
              ],
            },
            {
              id: 'dave_laughs',
              speaker: 'dave',
              text: '"Yeah, I get it. My first time here I topped my opening tee shot. Like, topped it. Went maybe forty yards."',
              next: null,
              responses: [],
              end: true,
            },
            {
              id: 'dave_eyebrow',
              speaker: 'dave',
              text: '"Visualizing? Like, with your eyes closed and everything? Alright, Tiger."',
              next: null,
              responses: [],
              end: true,
            },
            {
              id: 'dave_chuckles',
              speaker: 'dave',
              text: '"Hey, at least you\'re not the guy who teed off on the wrong hole last month. True story."',
              next: null,
              responses: [],
              end: true,
            },
          ],
          status: 'written',
        },
        phone: null,
      },
    },
    {
      number: 2,
      name: 'Hidden Angles',
      par: 5,
      yards: 502,
      theme: 'Dave tests you — he knows more than he should.',
      arcBeat: 'Dave reveals he knows your name, your team, your boss. This wasn\'t random. Sharon briefed him?',
      beats: {
        intro: { id: 'intro_h2', text: '', status: 'empty' },
        tee_thoughts: [],
        walking_1: { id: 'walk_h2', text: 'Dave asks what department you\'re in. He already knows.', choices: [], status: 'outline' },
        approach_thoughts: [],
        putt_thoughts: [],
        dialogue_tree: { id: 'dialogue_h2', nodes: [], status: 'empty' },
        phone: null,
      },
    },
    {
      number: 3,
      name: 'The Text',
      par: 4,
      yards: 388,
      theme: 'Sharon reaches out — who are you loyal to?',
      arcBeat: 'Sharon\'s first text. Casual on the surface, asks about Dave. The hook is set.',
      beats: {
        intro: { id: 'intro_h3', text: '', status: 'empty' },
        tee_thoughts: [],
        walking_1: { id: 'walk_h3', text: 'Your phone buzzes. Sharon.', choices: [], status: 'outline' },
        approach_thoughts: [],
        putt_thoughts: [],
        dialogue_tree: { id: 'dialogue_h3', nodes: [], status: 'empty' },
        phone: {
          id: 'phone_h3',
          from: 'sharon',
          type: 'text',
          preview: 'Hey! How\'s the round going?',
          fullText: 'Hey! How\'s the round going? Getting along with Dave? He\'s a good guy. Smart. Sometimes I wonder if he\'s too comfortable though, you know? Anyway, have fun out there. Tom might swing by the turn. 😊',
          responses: [
            { label: 'PLAY ALONG', text: 'Dave\'s great. Solid golfer.', setFlags: { cooperating_with_sharon: true }, traitEffects: { focus: -2 } },
            { label: 'DEFLECT', text: 'Just trying to play golf.', setFlags: { deflected_sharon: true }, traitEffects: { zen: 2 } },
            { label: 'LEAVE ON READ', text: '(Don\'t reply)', setFlags: { left_sharon_on_read: true }, traitEffects: { swagger: 2, zen: 3 } },
          ],
          status: 'written',
        },
      },
    },
    {
      number: 4, name: 'The Reach', par: 5, yards: 327,
      theme: 'Ambition — how far will you reach?',
      arcBeat: 'Dave mentions the Anderson Account directly.',
      beats: { intro: { id: 'intro_h4', text: '', status: 'empty' }, tee_thoughts: [], walking_1: null, approach_thoughts: [], putt_thoughts: [], dialogue_tree: { id: 'dialogue_h4', nodes: [], status: 'empty' }, phone: null },
    },
    {
      number: 5, name: 'The Chasm', par: 3, yards: 188,
      theme: 'Fear of failure — the stakes are real.',
      arcBeat: 'Anderson Account revealed. Tom might be watching. Pressure mounts.',
      beats: { intro: { id: 'intro_h5', text: '', status: 'empty' }, tee_thoughts: [], walking_1: null, approach_thoughts: [], putt_thoughts: [], dialogue_tree: { id: 'dialogue_h5', nodes: [], status: 'empty' }, phone: { id: 'phone_h5', from: 'sharon', type: 'text', preview: 'Quick heads up...', fullText: '', responses: [], status: 'outline' } },
    },
    {
      number: 6, name: 'The Truth', par: 4, yards: 316,
      theme: 'What do you value? Dave reveals something personal.',
      arcBeat: 'Dave opens up about being passed over. Or doesn\'t, depending on impression.',
      beats: { intro: { id: 'intro_h6', text: '', status: 'empty' }, tee_thoughts: [], walking_1: { id: 'walk_h6', text: 'Dave is quiet. Unusually quiet.', choices: [], status: 'outline' }, approach_thoughts: [], putt_thoughts: [], dialogue_tree: { id: 'dialogue_h6', nodes: [], status: 'empty' }, phone: null },
    },
    {
      number: 7, name: 'The Call', par: 3, yards: 106,
      theme: 'Can you keep it simple? Sharon calls.',
      arcBeat: 'Sharon calls (not texts). Wants a decision. Point of no return.',
      beats: { intro: { id: 'intro_h7', text: '', status: 'empty' }, tee_thoughts: [], walking_1: null, approach_thoughts: [], putt_thoughts: [], dialogue_tree: { id: 'dialogue_h7', nodes: [], status: 'empty' }, phone: { id: 'phone_h7', from: 'sharon', type: 'call', preview: 'INCOMING CALL', fullText: '', responses: [], status: 'outline' } },
    },
    {
      number: 8, name: 'The Moment', par: 4, yards: 418,
      theme: 'What kind of person are you? Everything converges.',
      arcBeat: 'The signature hole. Dave says something that lands differently based on every flag.',
      beats: { intro: { id: 'intro_h8', text: '', status: 'empty' }, tee_thoughts: [], walking_1: null, approach_thoughts: [], putt_thoughts: [], dialogue_tree: { id: 'dialogue_h8', nodes: [], status: 'empty' }, phone: null },
    },
    {
      number: 9, name: 'The Landing', par: 4, yards: 466,
      theme: 'Consequences — everything resolves.',
      arcBeat: 'Final hole. Endings branch based on flags and stats. Tom may appear.',
      beats: { intro: { id: 'intro_h9', text: '', status: 'empty' }, tee_thoughts: [], walking_1: null, approach_thoughts: [], putt_thoughts: [], dialogue_tree: { id: 'dialogue_h9', nodes: [], status: 'empty' }, phone: null },
    },
  ],

  endings: [
    { id: 'ending_ally', name: 'THE PARTNERSHIP', conditions: 'impression >= 70, warned_dave OR chose_dave, NOT used_dave_info', description: 'You and Dave leave as genuine allies.', text: '', status: 'outline' },
    { id: 'ending_rival', name: 'THE COMPETITION', conditions: 'impression 40-70, chose_career, NOT empathized_with_dave', description: 'Professional respect. Monday will be interesting.', text: '', status: 'outline' },
    { id: 'ending_betrayal', name: 'THE DEAL', conditions: 'cooperating_with_sharon, used_dave_info, NOT warned_dave', description: 'Sharon got what she needed. Dave doesn\'t know yet.', text: '', status: 'outline' },
    { id: 'ending_transcendent', name: 'THE ROUND', conditions: 'zen >= 80, chose_self, impression >= 50', description: 'You stopped caring about Anderson. Just golf.', text: '', status: 'outline' },
    { id: 'ending_collapse', name: 'THE SPIRAL', conditions: 'impression < 30, focus < 30 OR zen < 30', description: 'Everything fell apart. The parking lot is empty.', text: '', status: 'outline' },
  ],
};
