const BRAINSTORMS = [
  {
    id: 'bible-reader-features',
    date: '2026-04-15',
    title: 'Bible Reader — Feature Explosion',
    seed: 'A commentary-free KJV Bible reader with summary-first reading, Words of Jesus mode, and Argument Map mode. Deployed to GitHub Pages. What could it become?',
    winner: {
      rank: 1,
      title: 'The Manuscript View',
      score: 8.5,
      pitch: 'Show the Bible without chapter or verse numbers — they were added in the 1500s and aren\'t original. Just continuous flowing text with paragraph breaks where the manuscripts have them. Toggle between "Reference View" (numbered) and "Manuscript View" (how it was written). Nobody does this in a mobile reader.',
      risk: 'Users find the unfamiliar format disorienting rather than illuminating.',
      milestone: 'Prototype with one epistle (Philippians) rendered as continuous prose.',
    },
    stages: {
      stimuli: [
        { domain: 'Ecology', principle: 'Mycorrhizal Networks', connection: 'Bible verses don\'t stand alone — 344,000+ cross-references form an underground network. Tap a verse, see it light up connections to distant passages.' },
        { domain: 'Cognitive Science', principle: 'Spaced Repetition / Forgetting Curve', connection: 'We lose 70% of new info in 24 hours. The curated reading lists (Jesus mode, Argument Maps) are natural "decks" for a verse-fading memory system.' },
        { domain: 'Culinary Arts', principle: 'Mise en Place', connection: 'The two-depth model is already prep-before-cooking. Extend to "Cultural Map" (what did a 1st-century Jew know?) and "Genre Map" (this is apocalyptic — here\'s how to read it).' },
        { domain: 'Video Games', principle: 'Speedrunning Routing', connection: '"Read the Bible in a year" plans are routes, but boring. What about "The Justice Route" threading every passage about justice across 66 books?' },
        { domain: 'Music Theory', principle: 'Counterpoint', connection: 'KJV, ESV, WEB each carry a different melodic line of the same text. Side-by-side translation reveals nuances no single version captures.' },
      ],
      candidates: [
        { num: 1, title: 'Mycelium Mode — Cross-Reference Explorer', lens: 'practical', pitch: 'Tap any verse and see everywhere else in the Bible that references it. Treasury of Scripture Knowledge has ~500K cross-references, public domain. Wiki panel UX already handles this.', generic: 3, novel: 7, feasible: 7, kept: true },
        { num: 2, title: 'Full Offline PWA', lens: 'practical', pitch: 'Service worker + bundled KJV text (~4.5MB). Installable on phones, works with no internet. The app is 90% there already — just needs the SW layer.', generic: 4, novel: 5, feasible: 9, kept: true },
        { num: 3, title: 'Reading Streaks + Progress Grid', lens: 'practical', pitch: 'GitHub contribution graph for Bible reading. 1,189 chapters, 3.25 years at 1/day. Track which chapters you\'ve read at depth 1, localStorage, year-grid with colored squares.', generic: 4, novel: 5, feasible: 9, kept: true },
        { num: 4, title: 'Parallel Translation Toggle', lens: 'practical', pitch: 'bible-api.com supports WEB alongside KJV. Bible SDK offers NET with Strong\'s numbers. Toggle mid-chapter or show side-by-side.', generic: 4, novel: 5, feasible: 7, kept: false, cutReason: 'API rate-limit concerns with parallel fetching' },
        { num: 5, title: 'The Manuscript View', lens: 'inversion', pitch: 'Strip chapter and verse numbers (added in the 1500s). Show continuous prose with original paragraph breaks. Toggle: "Reference View" vs "Manuscript View." Nobody does this.', generic: 2, novel: 9, feasible: 7, kept: true },
        { num: 6, title: 'Anti-App — Printable PDF Export', lens: 'inversion', pitch: 'Select passages, export as beautifully typeset PDF via CSS @page rules. Physical paper, no screen. Churches print custom study sheets.', generic: 3, novel: 7, feasible: 6, kept: false, cutReason: 'CSS-to-PDF rendering is unreliable across browsers' },
        { num: 7, title: 'Silence Mode — One Verse, Empty Screen', lens: 'inversion', pitch: 'One verse centered on screen, nothing else. No header, footer, nav. Auto-advance on timer (30s/60s/2min). Digital lectio divina.', generic: 3, novel: 7, feasible: 9, kept: true },
        { num: 8, title: '500KB Ultralight Bible', lens: 'constraint', pitch: 'Entire app including all text in 500KB. Aggressive compression, font subsetting, load-on-demand. Loads instantly on 2G in Sub-Saharan Africa.', generic: 4, novel: 6, feasible: 5, kept: false, cutReason: 'Aggressive budgeting destroys the aesthetic' },
        { num: 9, title: 'No Scrolling — Card-Based Reading', lens: 'constraint', pitch: 'Nothing scrolls. Every piece of content fits on one "card." 2-3 verses per card, swipe to navigate. Instagram/TikTok trained a generation to consume content this way.', generic: 3, novel: 6, feasible: 7, kept: false, cutReason: 'Breaking verses into cards loses context' },
        { num: 10, title: 'Thematic Routes — Curated Reading Paths', lens: 'constraint', pitch: 'Never browse the full library. Enter through a route: "The Mercy Route" (15 passages Genesis to Revelation), "The Doubt Route" (Job, Ecclesiastes, lament Psalms, Thomas).', generic: 3, novel: 8, feasible: 7, kept: true },
      ],
      hybrids: [
        { title: 'Manuscript + Silence', parents: '#5 + #7', pitch: 'Continuous prose (no verse numbers) shown one paragraph at a time, centered, auto-advancing on a timer. The most contemplative way to read scripture digitally — letters as they were written, at a pace that forces you to sit with them.' },
        { title: 'Route + Streak', parents: '#10 + #3', pitch: 'Pick a thematic route (Mercy, Justice, Doubt, Women of the Bible). Track your progress as a streak. Each route is 15-30 passages spanning the whole canon — complete one, unlock the next. The progress grid shows routes completed, not just chapters.' },
        { title: 'Cross-Reference + Routes', parents: '#1 + #10', pitch: 'Instead of hand-curated routes, auto-generate them from the cross-reference network. Pick a starting verse, follow the cross-reference chain. Each reading session is a unique path through the network — you never read the same "route" twice.' },
      ],
      ranking: [
        { rank: 1, title: 'The Manuscript View', score: 8.5, fit: 9, feasible: 7, distinct: 9, resilient: 8 },
        { rank: 2, title: 'Route + Streak (Hybrid)', score: 8.0, fit: 9, feasible: 8, distinct: 7, resilient: 8 },
        { rank: 3, title: 'Full Offline PWA', score: 7.8, fit: 9, feasible: 9, distinct: 5, resilient: 9 },
        { rank: 4, title: 'Cross-Reference Explorer', score: 7.5, fit: 8, feasible: 7, distinct: 7, resilient: 7 },
        { rank: 5, title: 'Silence Mode', score: 7.0, fit: 8, feasible: 9, distinct: 7, resilient: 5 },
      ],
      challenges: [
        { title: 'The Manuscript View', perspective: 'Traditional Bible Reader', objection: 'I need verse numbers to find and share specific passages. This is form over function.', killShot: 'User tries to reference a passage in a group chat, can\'t cite it, switches back to numbered view permanently.', rebuttal: 'It\'s a toggle, not a replacement. Reference View is always one tap away. The point is experiencing the TEXT as literature, not a database. Both modes coexist.', confidence: 8 },
        { title: 'Route + Streak', perspective: 'Skeptical Pastor', objection: 'Gamifying Bible reading trivializes it. Streaks create guilt, not devotion.', killShot: 'User reads for the streak, not the content. Misses the point entirely.', rebuttal: 'The streak is gentle — no shaming, just a quiet record. The routes are the real value: curated thematic paths that show connections across the whole canon that linear reading misses.', confidence: 7 },
        { title: 'Full Offline PWA', perspective: 'Mobile Developer', objection: 'A 4.5MB initial download is a lot for a text app. Users on slow connections won\'t wait.', killShot: 'App store rejection for size, or users on 2G give up during first load.', rebuttal: 'This isn\'t an app store app — it\'s a PWA. The 4.5MB downloads in background after the shell loads. First meaningful paint is instant. And once cached, it works forever with zero network.', confidence: 9 },
      ],
    },
  },

  {
    id: 'shawnderwander-portfolio',
    date: '2026-04-16',
    title: 'ShawnDerWander — Portfolio Strategy',
    seed: 'The entire AI_SHAWNDERWANDER repo: 11 unrelated creative prototypes. What\'s the meta-play — how do scattered projects become more than the sum of their parts?',
    winner: {
      rank: 1,
      title: 'Bible Reader Deluxe',
      score: 8.0,
      pitch: 'Ship the Bible Reader as a full offline PWA with bundled KJV text, reading streak tracker, and all three modes polished — then release the chapter summaries, Jesus readings, and argument maps as open-data JSON on npm/GitHub. The app is the showcase; the data is the distribution channel.',
      risk: 'bible-api.com verse format may differ from bundled KJV, requiring normalization.',
      milestone: 'Bundle full KJV as local JSON, add service worker, verify airplane mode works.',
    },
    stages: {
      stimuli: [
        { domain: 'Biology', principle: 'Symbiosis', connection: 'Clownfish and anemones thrive together but die alone. The 11 projects are isolated — but Worm Man as a guide INSIDE other apps creates a recurring character that builds audience across projects.' },
        { domain: 'Culinary Arts', principle: 'Mise en Place', connection: 'A shared launch pad landing page is the prep that makes every future project discoverable the moment it ships.' },
        { domain: 'Electronic Music', principle: 'Modular Synthesis', connection: 'Each project is a Eurorack module. What if they could patch together? A shared event bus or web component standard.' },
        { domain: 'Game Design', principle: 'Roguelike Design', connection: 'A meta-game layer — unlock new stories/levels/characters across projects — creates a ShawnDerWander universe.' },
        { domain: 'Publishing', principle: 'Zine Culture', connection: 'The whole repo IS a digital zine — weird, unpolished, maximalist. Lean into that as the brand.' },
      ],
      candidates: [
        { num: 1, title: 'The Portfolio Hub', lens: 'practical', pitch: 'Deploy all 11 projects to one GitHub Pages site with a curated landing page. Each gets a card with screenshot and one-liner. Zero new code, just CI/CD config.', generic: 2, novel: 3, feasible: 10, kept: true },
        { num: 2, title: 'Worm Man Everywhere', lens: 'practical', pitch: 'A shared <worm-man-widget> web component any project can embed. He\'s a golf caddy, a Bible heckler, a story narrator. Uses Ollama HTTP API directly.', generic: 4, novel: 8, feasible: 6, kept: true },
        { num: 3, title: 'Ship the DAW', lens: 'practical', pitch: 'Package ShawnDerMixer properly: README, stem splitting optional, audio import/export. Browser DAWs are rare; one with AI stem splitting is rarer.', generic: 3, novel: 5, feasible: 5, kept: false, cutReason: 'Too much polish needed, not the strongest project' },
        { num: 4, title: 'Bible Reader Deluxe', lens: 'practical', pitch: 'Three quick wins that compound: service worker for offline, bundled KJV text, localStorage reading streaks. Turns a prototype into a daily-use tool.', generic: 4, novel: 5, feasible: 9, kept: true },
        { num: 5, title: 'Kill the Repo', lens: 'inversion', pitch: 'Spin each project into its own GitHub repo. Nobody stars a monorepo for one tool. Each gets its own README, Pages deploy, discoverability.', generic: 6, novel: 2, feasible: 8, kept: false, cutReason: 'Operationally tedious, low creative payoff' },
        { num: 6, title: 'The Anti-Portfolio', lens: 'inversion', pitch: 'One surreal interactive website where visitors DISCOVER projects by exploring. Click a wormhole, find Worm Man. Open a book, find Bible Reader. The portfolio itself is the art.', generic: 2, novel: 9, feasible: 4, kept: true },
        { num: 7, title: 'Open Source the Data', lens: 'inversion', pitch: 'The hand-written summaries for 1,189 chapters, 75 Jesus readings, and 12 argument maps are original content more valuable than the code. Package as open-data JSON.', generic: 3, novel: 7, feasible: 8, kept: true },
        { num: 8, title: '1-File Apps', lens: 'constraint', pitch: 'Every project in ONE self-contained .html file. Inline all CSS/JS. Drag-and-drop deploy, email-able, zero hosting. Perfect for sharing with non-technical people.', generic: 4, novel: 6, feasible: 7, kept: true },
        { num: 9, title: 'Local-First Creative Suite', lens: 'constraint', pitch: 'Nothing touches the network. Bundle all fonts, text, assets. Ship as a single Electron app. A creative suite for someone with no internet.', generic: 5, novel: 5, feasible: 4, kept: false, cutReason: 'Too niche, Electron packaging is painful' },
        { num: 10, title: '30-Day Sprint', lens: 'constraint', pitch: 'Ship one micro-project per day for 30 days. Each gets a single HTML file, screenshot, one-liner on the landing page. The sprint IS the product.', generic: 3, novel: 7, feasible: 5, kept: false, cutReason: 'Unsustainable solo, burns out the flow-state' },
      ],
      hybrids: [
        { title: 'The Worm Man Portal', parents: '#6 + #2', pitch: 'An interactive personal website where Worm Man IS the navigation. Chat with him, he guides you through projects. Each is a "room" he takes you to. Uses Ollama when available, scripted fallback when not.' },
        { title: 'Bible Reader Deluxe', parents: '#4 + #7', pitch: 'Ship the Bible Reader as a proper offline PWA with bundled text and streaks — then release the chapter summaries, Jesus readings, and argument maps as open-data JSON. App = showcase, data = distribution.' },
        { title: 'Portable Arcade', parents: '#8 + #1', pitch: 'Every project compressed into a single HTML file. Retro-styled "arcade" landing page where each is a clickable cabinet. Share any file by itself or browse the full collection.' },
      ],
      ranking: [
        { rank: 1, title: 'Bible Reader Deluxe', score: 8.0, fit: 9, feasible: 9, distinct: 7, resilient: 7 },
        { rank: 2, title: 'The Worm Man Portal', score: 7.3, fit: 8, feasible: 6, distinct: 9, resilient: 6 },
        { rank: 3, title: 'Portable Arcade', score: 6.8, fit: 7, feasible: 8, distinct: 7, resilient: 5 },
        { rank: 4, title: 'Worm Man Web Component', score: 6.8, fit: 7, feasible: 6, distinct: 7, resilient: 7 },
        { rank: 5, title: 'Open Source Bible Data', score: 6.8, fit: 6, feasible: 9, distinct: 6, resilient: 6 },
      ],
      challenges: [
        { title: 'Bible Reader Deluxe', perspective: 'Hostile Competitor (YouVersion)', objection: 'We have 500M installs. Your hand-written summaries cover 66 books; we have 2,000 reading plans in 70 languages.', killShot: 'Users try it once then go back to YouVersion\'s ecosystem.', rebuttal: 'YouVersion is bloated, ad-adjacent, commentary-heavy. There\'s a real audience that wants JUST the text with zero agenda. The open-data play means summaries spread even if the app doesn\'t.', confidence: 7 },
        { title: 'The Worm Man Portal', perspective: 'Skeptical Hiring Manager', objection: 'A talking worm as your portfolio UI? Nobody will take you seriously.', killShot: 'Hiring manager sees Worm Man, thinks "meme account," closes tab.', rebuttal: 'This isn\'t a resume — it\'s a creative showcase. A "serious mode" link at the bottom covers the edge case. For the RIGHT opportunities, Worm Man is a feature, not a bug.', confidence: 7 },
        { title: 'Portable Arcade', perspective: 'Impatient End User', objection: 'Why download HTML files when I can just use the website?', killShot: 'The 1-file constraint cripples complex projects (DAW can\'t work without server).', rebuttal: 'Not every project goes in the arcade — only ones that work as single files. The constraint curates quality. "Email this game to a friend" is genuinely delightful.', confidence: 5 },
      ],
    },
  },

  {
    id: 'bizarre-cross-pollinations',
    date: '2026-04-16',
    title: 'Bizarre Cross-Pollinations',
    seed: 'Find bizarre collisions between 11 projects in the ShawnDerWander ideas farm — a worm superhero NPC, a Bible reader, a golf melodrama, bedtime stories, a funk visualizer, a browser DAW, and more.',
    winner: {
      rank: 1,
      title: 'Argument Map: Absurd Logic',
      score: 8.8,
      pitch: 'Take the Bible Reader\'s argument-flow visualization and apply it to absurd content. Worm Man\'s case for beating Superman. The logical structure of a knock-knock joke. A conspiracy theory about Bird Guy. The serious format IS the comedy.',
      risk: 'Clinical format might suffocate the humor instead of enhancing it.',
      milestone: 'Write 3 absurd argument maps as raw data — zero new code needed.',
    },
    stages: {
      stimuli: [
        { domain: 'Architecture', principle: 'Parasitic Architecture', connection: 'Projects that grow ON other projects uninvited — Worm Man colonizing the Bible Reader.' },
        { domain: 'Game Design', principle: 'The Gaslighting Platformer', connection: 'A 2026 indie game where coins steal and spikes heal. Apps that betray your expectations.' },
        { domain: 'Surrealism', principle: 'Exquisite Corpse', connection: 'Content from one project transplanted into the frame of another, creating surreal juxtapositions.' },
        { domain: 'Ecology', principle: 'Mycorrhizal Networks', connection: 'Underground connections between projects that only emerge when you look.' },
        { domain: 'Literature', principle: 'The Unreliable Narrator', connection: 'An app whose own description of itself is wrong.' },
      ],
      candidates: [
        { num: 1, title: 'Worm Man Reads Scripture', lens: 'practical', pitch: 'An opt-in toggle in the Bible Reader where Worm Man provides AI comedy commentary on whatever passage you\'re reading via Ollama.', generic: 3, novel: 8, feasible: 7, kept: true },
        { num: 2, title: 'The Adequates: Shared Universe', lens: 'practical', pitch: 'All characters from all projects exist in one fictional world. Dave is Worm Man\'s parole officer. A "lore bible" ties it together.', generic: 4, novel: 7, feasible: 3, kept: false, cutReason: 'Too ambitious, pure narrative design' },
        { num: 3, title: 'Argument Map: Absurd Logic', lens: 'practical', pitch: 'The Bible Reader\'s argument-map visualization applied to non-Bible content. Map Worm Man\'s reasoning. Map joke structures. Map conspiracy theories.', generic: 2, novel: 9, feasible: 8, kept: true },
        { num: 4, title: 'Lullaby Karaoke', lens: 'practical', pitch: 'Lyric visualizer effects + Web Speech API. Parents sing a lullaby and the words appear on screen with drip/vortex/ember effects.', generic: 4, novel: 6, feasible: 5, kept: false, cutReason: 'Speech recognition + kids = unreliable' },
        { num: 5, title: 'The App That Gaslights You', lens: 'inversion', pitch: 'An app that presents itself as one project but subtly lies — Bible text replaced with Worm Man quotes, golf holes become UX briefs. Tap the lies.', generic: 2, novel: 9, feasible: 6, kept: true },
        { num: 6, title: 'Anti-Visualizer', lens: 'inversion', pitch: 'Instead of visualizing audio by adding to the screen, this removes. Music erases content. Silence = blank page.', generic: 3, novel: 7, feasible: 6, kept: false, cutReason: 'One-note visual gag' },
        { num: 7, title: 'Dave\'s Secret Bible Study', lens: 'inversion', pitch: 'In the golf game, Dave is secretly reading scripture between holes. The corporate melodrama gets an existential faith undercurrent.', generic: 2, novel: 8, feasible: 4, kept: false, cutReason: 'Requires deep golf game rewrite' },
        { num: 8, title: 'The Chaos Deck', lens: 'constraint', pitch: 'All content becomes cards. Every Bible verse, Worm Man quote, joke, golf line — one massive deck. Deal 5, build a surreal "argument." Screenshot and share.', generic: 3, novel: 8, feasible: 8, kept: true },
        { num: 9, title: 'One Screen, All Projects', lens: 'constraint', pitch: 'All 11 projects run simultaneously, tiled like CCTV. They interact: Worm Man\'s chat drives Bible search, music drives the lyric visualizer.', generic: 3, novel: 8, feasible: 3, kept: false, cutReason: 'Technically nightmarish' },
        { num: 10, title: 'The Confession Booth', lens: 'constraint', pitch: 'Voice-only input via Web Speech API. Worm Man responds via Ollama. App shows a matched Bible verse, a joke, and a logic node analyzing your confession.', generic: 2, novel: 9, feasible: 6, kept: true },
      ],
      hybrids: [
        { title: 'Worm Man\'s Confession Booth', parents: '#1 + #10', pitch: 'Confess to Worm Man via voice. He responds in character. The app shows a Bible verse, a joke, and an argument-map node — four outputs from one input. Sacred meets profane meets analytical.' },
        { title: 'Chaos Deck: Argument Edition', parents: '#3 + #8', pitch: 'Every card is an argument-map node. Content from all projects. Deal 5 cards, arrange them into the most coherent (or absurd) argument. Share as screenshot.' },
        { title: 'The Gaslighting Card Game', parents: '#5 + #8', pitch: 'Cards from the wrong project sneak in. Tap the imposters. Difficulty escalates — early fakes are obvious, late ones almost fit.' },
      ],
      ranking: [
        { rank: 1, title: 'Argument Map: Absurd Logic', score: 8.8, fit: 9, feasible: 9, distinct: 9, resilient: 8 },
        { rank: 2, title: 'Worm Man\'s Confession Booth', score: 7.0, fit: 7, feasible: 6, distinct: 9, resilient: 6 },
        { rank: 3, title: 'The App That Gaslights You', score: 7.0, fit: 7, feasible: 7, distinct: 8, resilient: 6 },
        { rank: 4, title: 'Chaos Deck: Argument Edition', score: 6.5, fit: 6, feasible: 7, distinct: 7, resilient: 6 },
        { rank: 5, title: 'Chaos Deck: Simple', score: 5.8, fit: 5, feasible: 8, distinct: 5, resilient: 5 },
      ],
      challenges: [
        { title: 'Argument Map: Absurd Logic', perspective: 'Comedy Writer', objection: 'Logic diagrams kill comedy. Jokes work because of timing and surprise.', killShot: 'User sees a clinical flowchart, thinks "this isn\'t funny," closes it.', rebuttal: 'The comedy IS the contrast. Same mechanism as a deadpan Wikipedia article about something ridiculous. The format is PART of the joke.', confidence: 8 },
        { title: 'Worm Man\'s Confession Booth', perspective: 'Religious Community', objection: 'Pairing an uncensored comedy worm with Bible verses trivializes scripture.', killShot: 'A screenshot of Worm Man\'s crude response next to a verse about suffering goes viral in the wrong way.', rebuttal: 'Worm Man is too absurd to be mistaken for theological authority. Bible verses are presented straight. But verse curation is critical.', confidence: 6 },
        { title: 'The App That Gaslights You', perspective: 'Mobile Gamer', objection: '10 rounds and I\'m done. Where\'s the replay value?', killShot: 'User finishes in 8 minutes, scores perfectly, leaves.', rebuttal: 'Endless mode with procedural generation solves this. The game is a discovery funnel to other projects.', confidence: 6 },
      ],
    },
  },
  {
    id: 'writing-room-compelling',
    date: '2026-04-15',
    title: 'Making the Writing Room Actually Compelling',
    seed: 'The Madison AI Suite\'s Writing Room is a turn-based collaborative AI writing tool where AI personas take structured creative rounds. Backend works, frontend is stubbed. The challenge: why would anyone use this over just chatting with ChatGPT?',
    winner: {
      rank: 1,
      title: 'The Showrunner\'s Table',
      score: 8.3,
      pitch: 'You direct a room of AI writers who actually push back — like being a TV showrunner with opinionated staff. You give direction, never prose. The producer agent challenges your decisions when they contradict story logic. Override if you want, but the system tracks "creative debt" — unresolved tensions flagged on the output.',
      risk: 'Users find pushback annoying and go back to obedient ChatGPT.',
      milestone: 'Remove COMING SOON stub, wire up existing backend, implement director-only input mode with producer pushback.',
    },
    stages: {
      stimuli: [
        'TV Writers\' Room — Real rooms run on hierarchy and DISAGREEMENT, not polite consensus. Showrunner → staff writer → rewrite cycle.',
        '"Yes, And" (Improv Comedy) — Viola Spolin\'s 1940s theater games: never reject, only build. Momentum over editing.',
        'Oxford Debate — ARGUS framework and TreeDebater (ICLR 2026) show adversarial AI produces 15.6% more persuasive output than agreeable agents.',
        'Culinary Brigade — Escoffier\'s brigade de cuisine: each station (saucier, grill, pastry) does a DIFFERENT specialized job. Chef directs; stations execute.',
        'Jazz Ensemble — Musicians "trade fours," soloing over shared chord changes. Each solo responds to the last. Fixed structure, free expression.',
      ],
      candidates: [
        { title: 'The Disagreement Engine', lens: 'Practical', pitch: 'Force agents to ARGUE. One agent is a permanent devil\'s advocate. Oxford-debate research shows adversarial AI produces 15.6% better output. The room has TENSION, not just turns.', score: 7.3, kept: true },
        { title: 'Artifact-First Writing', lens: 'Practical', pitch: 'The room produces a LIVING DOCUMENT, not chat messages. Conversation is a sidebar; main panel is always the manuscript. Agent suggestion blocks with accept/reject — not a full editor, just structured proposals on a text artifact.', score: 6.3, kept: true },
        { title: 'Genre Templates + Auto-Casting', lens: 'Practical', pitch: 'Offer templates (TV Pilot, Short Story, Game Quest) that pre-configure rounds, personas, and output format.', score: 5.7, kept: false },
        { title: 'Visual Integration — Concept Art to Story', lens: 'Practical', pitch: 'Drag generated concept art from Madison Suite\'s visual labs into the Writing Room. Agents write backstory, dialogue, and gameplay role from the image. Nobody else connects image gen to writing.', score: 5.7, kept: true },
        { title: 'Kill the Rounds', lens: 'Inversion', pitch: 'Replace the 7-round structure with freeform input. The room is always-on, not phased.', score: 5.7, kept: false },
        { title: 'You Don\'t Write — You Direct', lens: 'Inversion', pitch: 'Invert the user\'s role. You never type prose — only DIRECTION: "Make the villain more sympathetic." Agents do ALL the writing. You\'re the showrunner, not a staff writer. Inspired by the culinary brigade.', score: 6.0, kept: true },
        { title: 'The Room Fights Back', lens: 'Inversion', pitch: 'Give agents OPINIONS. The producer can reject your direction: "That doesn\'t work because X." Override comes with "creative debt" — tracked unresolved conflicts flagged on the output.', score: 5.7, kept: true },
        { title: 'One-Page Output', lens: 'Constraint', pitch: 'The room MUST produce a single, finished one-page document. Not a chat log. Forces agents to converge. Each session produces one polished creative artifact.', score: 6.0, kept: true },
        { title: '3 Turns Total', lens: 'Constraint', pitch: 'Entire room runs in exactly 3 turns. Pitch → debate → final draft. Output in under 60 seconds.', score: 6.0, kept: false },
        { title: 'Offline / Local Mode (Ollama)', lens: 'Constraint', pitch: 'Works without internet using Ollama on RTX 5090. Swap Gemini for local 32B models. Private, fast, no API costs.', score: 5.3, kept: false },
      ],
      hybrids: [
        { title: 'The Showrunner\'s Table', parents: ['You Don\'t Write — You Direct', 'The Room Fights Back'], pitch: 'You\'re the showrunner — directing, never writing prose. Agents pitch, draft, and argue. The producer challenges decisions that contradict story logic. Override if you want, but "creative debt" tracks unresolved tensions. The FRICTION is the feature.' },
        { title: 'Concept-to-Script', parents: ['Visual Integration', 'One-Page Output'], pitch: 'Drag concept art in, get a polished one-page document out — character sheet, scene card, or pitch deck. Visual input → formatted textual artifact in one flow. Each session produces one stackable creative card.' },
        { title: 'The Living Draft', parents: ['The Disagreement Engine', 'Artifact-First Writing'], pitch: 'Main panel is the evolving document. Agents debate IN THE MARGINS like Google Docs comments. One writes a paragraph; another challenges with a competing version as a diff. User resolves conflicts by picking winners.' },
      ],
      ranking: [
        { rank: 1, title: 'The Showrunner\'s Table', score: 8.3, pitch: 'You direct; agents push back. Creative debt tracks overrides. TV showrunner with opinionated AI staff.', risk: 'Users find pushback annoying.', milestone: 'Remove stub, wire backend, implement director mode + producer pushback.' },
        { rank: 2, title: 'Concept-to-Script', score: 7.5, pitch: 'Drag concept art → get polished one-page character sheet or scene card. Unique to Madison Suite.', risk: '90% of users may never use visual tools.', milestone: 'Image drop zone + Gemini vision + character sheet template.' },
        { rank: 3, title: 'The Living Draft', score: 7.3, pitch: 'Document-first with agent debate in margins. Accept/reject suggestion blocks. Not a chat log.', risk: 'Scope creep into building a full document editor.', milestone: 'Split panel layout + suggestion blocks with accept/reject.' },
        { rank: 3, title: 'The Disagreement Engine', score: 7.3, pitch: 'Adversarial agents produce 15.6% better output. Mandatory challenge phase in each round.', risk: 'Fake disagreement from one model feels hollow.', milestone: 'Add challenge phase + devil\'s advocate agent role.' },
        { rank: 5, title: 'One-Page Output', score: 7.0, pitch: 'Every session produces one polished page. Pages library accumulates into larger works.', risk: 'Too constraining for long-form writers.', milestone: 'Finalize button + formatted output + pages library.' },
      ],
      challenges: [
        { title: 'The Showrunner\'s Table', perspective: 'Impatient End User', objection: 'I just want the AI to write. Why is it arguing with me?', killShot: 'User gets pushback on first direction, thinks it\'s broken, goes back to ChatGPT.', rebuttal: 'Friction slider defaults to mild/agreeable. Oxford research shows 15.6% quality improvement. Override mechanic makes it a game, not an obstacle.', confidence: 8 },
        { title: 'The Living Draft', perspective: 'Solo Developer', objection: 'Building a collaborative editor with diff/merge is months of work for one person.', killShot: 'Scope creep turns Writing Room into a document editor project. Six months later: mediocre editor, no writing room.', rebuttal: 'No full editor. Simple markdown panel with structured suggestion cards. Accept/reject buttons, not cursor sharing. Weekend of React, not months.', confidence: 7 },
        { title: 'Concept-to-Script', perspective: 'Typical Writer', objection: 'I don\'t use concept art tools. This visual integration is irrelevant to me.', killShot: '90% never open concept labs. Dev time wasted on a niche feature.', rebuttal: 'Madison Suite\'s primary audience IS game artists. Text briefs still work. Gemini vision is ~20 lines of code — minimal investment, massive differentiation.', confidence: 7 },
        { title: 'The Disagreement Engine', perspective: 'Creative Professional', objection: 'AI disagreement is theater — one model roleplaying both sides.', killShot: 'Users see through the gimmick, trust erodes.', rebuttal: 'Different model tiers, temperature settings, and persona prompts produce genuinely different outputs. Doesn\'t need to be "real" — needs to be USEFUL.', confidence: 7 },
        { title: 'One-Page Output', perspective: 'Power User / Novelist', objection: 'One page? I\'m writing a novel. This is a toy for LinkedIn posts.', killShot: 'Serious writers need 80K words. No path to manuscript = they leave for Sudowrite.', rebuttal: 'One page per SESSION. Sessions chain via Pages library. Think "one scene," not "one page." The constraint ensures finished output, not endless chat logs.', confidence: 6 },
      ],
    },
  },
];
