// ─── Poetry & Wisdom (Job, Psalms, Proverbs, Ecclesiastes, Song of Solomon) ───
// Chapter summaries; verse text from bible-api.com

ALL_BOOKS.push({
  title: "Job",
  shortTitle: "Job",
  apiBook: "job",
  section: "poetry",
  chapters: 42,
  pages: [
    {
      chapter: 1,
      title: "Satan's Challenge",
      summary: "In heaven Satan challenges Job's integrity; Job loses children, servants, and wealth in one day yet blesses God instead of sinning.",
      wikiTerms: [],
    },
    {
      chapter: 2,
      title: "Satan Strikes Job",
      summary: "Satan afflicts Job with painful sores; his wife urges him to curse God, but Job refuses and does not charge God with wrong.",
      wikiTerms: [],
    },
    {
      chapter: 3,
      title: "Job Curses His Day",
      summary: "Job breaks silence and curses the day he was born, longing for darkness and death rather than his bitter suffering.",
      wikiTerms: [],
    },
    {
      chapter: 4,
      title: "Eliphaz Speaks",
      summary: "Eliphaz the Temanite suggests the innocent do not perish as Job has; he implies suffering must have a moral cause in Job himself.",
      wikiTerms: [],
    },
    {
      chapter: 5,
      title: "Eliphaz Urges Appeal",
      summary: "Eliphaz tells Job to commit his cause to God, who rescues the suffering, wounds to heal, and frustrates the crafty.",
      wikiTerms: [],
    },
    {
      chapter: 6,
      title: "Job Answers Eliphaz",
      summary: "Job insists his complaint is justified—his arrows pierce him—and he longs for death more than hidden treasure.",
      wikiTerms: [],
    },
    {
      chapter: 7,
      title: "Job's Hard Service",
      summary: "Job compares life to hard labor, months of futility, and restless nights without hope of relief.",
      wikiTerms: [],
    },
    {
      chapter: 8,
      title: "Bildad Speaks",
      summary: "Bildad insists God does not pervert justice; if Job were pure, God would restore him—darkly hinting his children died for guilt.",
      wikiTerms: [],
    },
    {
      chapter: 9,
      title: "Job Defends His Innocence",
      summary: "Job wishes for a mediator between God and man; though God seems to crush him, Job maintains his blamelessness.",
      wikiTerms: [],
    },
    {
      chapter: 10,
      title: "Job on God's Hiddenness",
      summary: "Job asks why God hides His face and treats him like an enemy if Job has done no wrong.",
      wikiTerms: [],
    },
    {
      chapter: 11,
      title: "Zophar Speaks",
      summary: "Zophar urges Job to repent and put away iniquity so he may lift up his face without spot and forget trouble.",
      wikiTerms: [],
    },
    {
      chapter: 12,
      title: "Job Mocks the Counselors",
      summary: "Job calls his friends worthless physicians; wisdom and might belong to God alone, who humbles proud counselors.",
      wikiTerms: [],
    },
    {
      chapter: 13,
      title: "Though He Slay Me",
      summary: "Job trusts God even in death, asks God to show his sin, and begs relief from terrifying visions.",
      wikiTerms: [],
    },
    {
      chapter: 14,
      title: "Mortality and Hope",
      summary: "Man's days are few and full of trouble; like a flower he fades—yet Job asks whether mortals might live again after death.",
      wikiTerms: [],
    },
    {
      chapter: 15,
      title: "Eliphaz Accuses",
      summary: "Eliphaz says the wicked suffer terrors and darkness—implying Job fits the pattern of the godless and arrogant.",
      wikiTerms: [],
    },
    {
      chapter: 16,
      title: "Miserable Comforters",
      summary: "Job calls his friends miserable comforters; yet he knows his witness is in heaven and his advocate lives.",
      wikiTerms: [],
    },
    {
      chapter: 17,
      title: "Broken Spirit",
      summary: "Job's spirit is broken; he asks for the grave as rest and says his friends mock him while God has hedged him in.",
      wikiTerms: [],
    },
    {
      chapter: 18,
      title: "Bildad on the Wicked",
      summary: "Bildad paints the wicked snared, plunged in darkness, terror, and roots dried up—Job hears the insult.",
      wikiTerms: [],
    },
    {
      chapter: 19,
      title: "My Redeemer Lives",
      summary: "Job feels God and friends have turned against him, yet declares his Redeemer lives and will stand on earth at last.",
      wikiTerms: [],
    },
    {
      chapter: 20,
      title: "Zophar on Brief Triumph",
      summary: "Zophar says the wicked's joy is short and his gain cannot endure—God will cast him down in anger.",
      wikiTerms: [],
    },
    {
      chapter: 21,
      title: "The Wicked Prosper",
      summary: "Job observes that wicked men often live long in ease, exposing his friends' tidy theology as inadequate.",
      wikiTerms: [],
    },
    {
      chapter: 22,
      title: "Eliphaz's Harsh Charge",
      summary: "Eliphaz accuses Job of oppressing the poor and asks what pleasure God could take in such great wickedness.",
      wikiTerms: [],
    },
    {
      chapter: 23,
      title: "Where Is God?",
      summary: "Job longs to find God's court to plead his case; he goes forward and backward but cannot perceive God's path.",
      wikiTerms: [],
    },
    {
      chapter: 24,
      title: "Times of Judgment",
      summary: "Job describes God's ordering of land and light and asks why wrongdoers seem to prolong their power without reckoning.",
      wikiTerms: [],
    },
    {
      chapter: 25,
      title: "How Can Man Be Just?",
      summary: "Bildad asks how mortal man can be righteous before God—before whom even stars are not pure.",
      wikiTerms: [],
    },
    {
      chapter: 26,
      title: "Job Affirms God's Majesty",
      summary: "Job answers with sarcasm, then soars in poetry about God's power over death, Sheol, and the vault of heaven.",
      wikiTerms: [],
    },
    {
      chapter: 27,
      title: "Job Holds His Integrity",
      summary: "Job swears by the living God that he will not call false comfort good—God will judge both righteous and wicked.",
      wikiTerms: [],
    },
    {
      chapter: 28,
      title: "The Hymn to Wisdom",
      summary: "A poem asks where wisdom is found—not in mines or seas—and declares that God alone knows its way and place.",
      wikiTerms: [],
    },
    {
      chapter: 29,
      title: "Job's Former Honor",
      summary: "Job recalls his honored place at the gate, helping the poor and being respected as a father to the needy.",
      wikiTerms: [],
    },
    {
      chapter: 30,
      title: "From Honor to Shame",
      summary: "Young men now mock Job; he sits in dust though he wept for the afflicted and sang in the darkest nights.",
      wikiTerms: [],
    },
    {
      chapter: 31,
      title: "Job's Oath of Innocence",
      summary: "Job solemnly denies lust, falsehood, adultery, mistreatment of servants, and trusting in gold instead of God.",
      wikiTerms: [],
    },
    {
      chapter: 32,
      title: "Elihu Appears",
      summary: "Young Elihu burns with anger at Job and the friends; he speaks because they have no answer and his words press on him.",
      wikiTerms: [],
    },
    {
      chapter: 33,
      title: "Elihu on God's Speech",
      summary: "Elihu says God speaks in dreams and pain to turn pride aside and preserve the soul from the pit.",
      wikiTerms: [],
    },
    {
      chapter: 34,
      title: "Elihu on Justice",
      summary: "Elihu defends God's justice—He is mighty and just, shows no partiality, and governs nations and kings.",
      wikiTerms: [],
    },
    {
      chapter: 35,
      title: "Elihu on God's Greatness",
      summary: "Elihu declares God is exalted above justice; He looks on the proud and the cry of the afflicted.",
      wikiTerms: [],
    },
    {
      chapter: 36,
      title: "Elihu on God's Rule",
      summary: "Elihu urges Job to consider God's wondrous works in clouds, lightning, and the ordering of storm and rain.",
      wikiTerms: [],
    },
    {
      chapter: 37,
      title: "Elihu's Final Words",
      summary: "Elihu describes God's voice in thunder and storm, His command of weather, and the breath of the Almighty creating ice and fair skies.",
      wikiTerms: [],
    },
    {
      chapter: 38,
      title: "God from the Whirlwind",
      summary: "The Lord answers Job out of the whirlwind, questioning where Job was when He laid the earth's foundations and set its bounds.",
      wikiTerms: [],
    },
    {
      chapter: 39,
      title: "Wild Creatures",
      summary: "God continues with mountain goats, wild donkey, ostrich, horse, hawk, and eagle—creation's freedom beyond human harness.",
      wikiTerms: [],
    },
    {
      chapter: 40,
      title: "Behemoth and Humility",
      summary: "God points to Behemoth's might; Job answers briefly—God challenges Job to humble the proud if he can.",
      wikiTerms: [],
    },
    {
      chapter: 41,
      title: "Leviathan Unmatched",
      summary: "The Lord details Leviathan's scales, breath, and terror—no one can tame him; he is king over all proud beasts.",
      wikiTerms: [],
    },
    {
      chapter: 42,
      title: "Restored and Reconciled",
      summary: "Job repents in dust and ashes; God rebukes the friends and commands sacrifice; Job's fortunes are restored double.",
      wikiTerms: [],
    },
  ],
});
ALL_BOOKS.push({
  title: "Psalms",
  shortTitle: "Psalms",
  apiBook: "psalms",
  section: "poetry",
  chapters: 150,
  pages: [
    {
      chapter: 1,
      title: "Two Paths",
      summary: "Blessed is the one who delights in God's law; the wicked are like chaff driven away—two ways, two ends.",
      wikiTerms: [],
    },
    {
      chapter: 2,
      title: "The Nations Rage",
      summary: "Earth's rulers conspire against the Lord and His Anointed; God laughs and installs His King on Zion.",
      wikiTerms: [],
    },
    {
      chapter: 3,
      title: "Morning Prayer of Trust",
      summary: "Many rise against the psalmist; he sleeps and wakes because the Lord sustains him—salvation belongs to God.",
      wikiTerms: [],
    },
    {
      chapter: 4,
      title: "Evening Confidence",
      summary: "Answer me when I call; in peace I will lie down, for You alone make me dwell in safety.",
      wikiTerms: [],
    },
    {
      chapter: 5,
      title: "Morning Guidance",
      summary: "Lead me in righteousness; destroy those who speak lies and bloodshed; let me enter Your house with joy.",
      wikiTerms: [],
    },
    {
      chapter: 6,
      title: "Penitential Plea",
      summary: "Rebuke me not in anger; heal my bones; how long, O Lord?—deliver me for Your steadfast love's sake.",
      wikiTerms: [],
    },
    {
      chapter: 7,
      title: "Vindication",
      summary: "Let my enemy be caught in his schemes; let the Lord judge the peoples—He tests hearts and reins.",
      wikiTerms: [],
    },
    {
      chapter: 8,
      title: "God and Humanity",
      summary: "When I consider the heavens, what is man that You care for him—yet You crown him with glory and honor.",
      wikiTerms: [],
    },
    {
      chapter: 9,
      title: "Thanksgiving for Justice",
      summary: "I will praise You with my whole heart; the Lord sits enthroned forever judging righteously.",
      wikiTerms: [],
    },
    {
      chapter: 10,
      title: "Why Do the Wicked Prosper?",
      summary: "The helpless are crushed while the wicked boast \"God will not see\"—yet God sees and will arise.",
      wikiTerms: [],
    },
    {
      chapter: 11,
      title: "Refuge in the Lord",
      summary: "In the Lord I take refuge; the foundations may be removed, yet the upright shall behold His face.",
      wikiTerms: [],
    },
    {
      chapter: 12,
      title: "Help, Lord",
      summary: "Faithful people vanish; everyone lies—cut off flattering lips that say \"Our tongue will prevail.\"",
      wikiTerms: [],
    },
    {
      chapter: 13,
      title: "How Long?",
      summary: "How long will You hide Your face?—yet I will trust in Your steadfast love and rejoice in Your salvation.",
      wikiTerms: [],
    },
    {
      chapter: 14,
      title: "The Fool Says No God",
      summary: "They are corrupt; none does good—God looks from heaven for one who understands and seeks Him.",
      wikiTerms: [],
    },
    {
      chapter: 15,
      title: "Who May Dwell?",
      summary: "Who may abide on Your holy hill?—the blameless walker, truth-speaker, and one who fears the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 16,
      title: "My Portion and Cup",
      summary: "The Lord is my chosen inheritance; beautiful pleasures are at His right hand—I will not be shaken.",
      wikiTerms: [],
    },
    {
      chapter: 17,
      title: "Under His Wings",
      summary: "Keep me as the apple of Your eye; hide me from wicked foes who surround me—when I awake I shall be satisfied.",
      wikiTerms: [],
    },
    {
      chapter: 18,
      title: "Royal Thanksgiving",
      summary: "The Lord delivered David from all enemies—He bowed the heavens and brought him out into a broad place.",
      wikiTerms: [],
    },
    {
      chapter: 19,
      title: "Heavens and Law",
      summary: "The heavens declare God's glory; His law revives the soul, enlightens the eyes, and is more desirable than gold.",
      wikiTerms: [],
    },
    {
      chapter: 20,
      title: "Prayer for the King",
      summary: "May the Lord answer in trouble, send help from Zion, and fulfill all the desires of Your heart.",
      wikiTerms: [],
    },
    {
      chapter: 21,
      title: "The King Rejoices",
      summary: "The king rejoices in God's strength; You give him long life and victory over his enemies.",
      wikiTerms: [],
    },
    {
      chapter: 22,
      title: "My God, Why?",
      summary: "Why have You forsaken me?—yet You brought me from the womb; deliver me from the mouth of the lion.",
      wikiTerms: [],
    },
    {
      chapter: 23,
      title: "The Good Shepherd",
      summary: "The Lord is my shepherd—I shall not want; He leads, restores, and prepares a table in the presence of enemies.",
      wikiTerms: [],
    },
    {
      chapter: 24,
      title: "Earth Is the Lord's",
      summary: "Who may ascend the hill of the Lord?—clean hands and pure heart—lift up your heads, everlasting gates.",
      wikiTerms: [],
    },
    {
      chapter: 25,
      title: "Teach Me Your Ways",
      summary: "To You I lift my soul; lead me in truth; remember mercy, not sins—friendship is for those who fear the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 26,
      title: "Integrity",
      summary: "Vindicate me, for I have walked in integrity; I wash my hands in innocence and bless the Lord in the congregation.",
      wikiTerms: [],
    },
    {
      chapter: 27,
      title: "Light and Salvation",
      summary: "The Lord is my light—whom shall I fear?—wait for the Lord; be strong; He will hide me in His tent.",
      wikiTerms: [],
    },
    {
      chapter: 28,
      title: "The Lord Is Strength",
      summary: "To You I cry; be not deaf—bless the Lord—He is the saving strength of His anointed.",
      wikiTerms: [],
    },
    {
      chapter: 29,
      title: "Voice of the Lord",
      summary: "Ascribe to the Lord glory and strength—His voice thunders over waters and strips forests bare in holiness.",
      wikiTerms: [],
    },
    {
      chapter: 30,
      title: "From Weeping to Joy",
      summary: "You drew me up and healed me—weeping may tarry for the night, but joy comes with the morning.",
      wikiTerms: [],
    },
    {
      chapter: 31,
      title: "Into Your Hand",
      summary: "Into Your hand I commit my spirit; You have redeemed me—let Your face shine on Your servant in distress.",
      wikiTerms: [],
    },
    {
      chapter: 32,
      title: "Forgiven",
      summary: "Blessed is the one whose transgression is forgiven—when I kept silent I wasted away; You are my hiding place.",
      wikiTerms: [],
    },
    {
      chapter: 33,
      title: "Rejoice in the Lord",
      summary: "Sing a new song—by the word of the Lord the heavens were made—He looks on all who fear Him.",
      wikiTerms: [],
    },
    {
      chapter: 34,
      title: "Taste and See",
      summary: "I will bless the Lord at all times—taste and see that the Lord is good; those who seek Him lack nothing.",
      wikiTerms: [],
    },
    {
      chapter: 35,
      title: "Contend for Me",
      summary: "Plead my cause against those who contend with me—let shame cover them—my soul shall rejoice in the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 36,
      title: "Steadfast Love",
      summary: "Your steadfast love reaches the heavens; with You is the fountain of life—in Your light we see light.",
      wikiTerms: [],
    },
    {
      chapter: 37,
      title: "Fret Not",
      summary: "Do not fret over evildoers—they wither like grass; trust in the Lord and do good—He will give you the desires of your heart.",
      wikiTerms: [],
    },
    {
      chapter: 38,
      title: "Heavy Guilt",
      summary: "Your arrows pierce me; there is no soundness—do not forsake me, O Lord my salvation.",
      wikiTerms: [],
    },
    {
      chapter: 39,
      title: "Brevity of Life",
      summary: "Bridle my mouth—my days are a handbreadth; hear my prayer before I depart and am no more.",
      wikiTerms: [],
    },
    {
      chapter: 40,
      title: "I Waited",
      summary: "I waited patiently—He drew me from the pit and put a new song in my mouth—delight to do Your will, O God.",
      wikiTerms: [],
    },
    {
      chapter: 41,
      title: "Blessed to the Poor",
      summary: "Blessed is he who considers the poor—You preserve him on his sickbed—even my friend betrayed me.",
      wikiTerms: [],
    },
    {
      chapter: 42,
      title: "As the Deer Pants",
      summary: "As a deer pants for water, so my soul pants for God—why cast down? Hope in God; I shall praise Him again.",
      wikiTerms: [],
    },
    {
      chapter: 43,
      title: "Send Light and Truth",
      summary: "Judge me, O God—send Your light and truth; why are you cast down? Hope in God who is my exceeding joy.",
      wikiTerms: [],
    },
    {
      chapter: 44,
      title: "We Have Heard",
      summary: "Our fathers told us Your deeds—yet You have rejected us; for Your sake we face death all day—awake; do not forget us.",
      wikiTerms: [],
    },
    {
      chapter: 45,
      title: "Royal Wedding",
      summary: "The king's lips drip grace—gird on Your sword—Your throne is forever—daughter, forget your people; the King desires your beauty.",
      wikiTerms: [],
    },
    {
      chapter: 46,
      title: "Our Refuge",
      summary: "God is our refuge—though earth be removed—we will not fear—He makes wars cease to the ends of the earth.",
      wikiTerms: [],
    },
    {
      chapter: 47,
      title: "Clap Your Hands",
      summary: "Clap, all peoples—God is King over all the earth—He subdues nations under our feet—sing praises with understanding.",
      wikiTerms: [],
    },
    {
      chapter: 48,
      title: "Great Is the Lord in Zion",
      summary: "Walk about Zion—tell the next generation—God is our God forever; He will guide us beyond death.",
      wikiTerms: [],
    },
    {
      chapter: 49,
      title: "Ransom of the Soul",
      summary: "Why should I fear when I see the rich?—no ransom avails on the day of death—God will redeem my soul.",
      wikiTerms: [],
    },
    {
      chapter: 50,
      title: "God Shines Forth",
      summary: "God calls heaven and earth—He owns cattle on a thousand hills—offer thanksgiving as sacrifice and call on Me in trouble.",
      wikiTerms: [],
    },
    {
      chapter: 51,
      title: "Have Mercy",
      summary: "Have mercy—blot out my transgressions—against You only have I sinned—create in me a clean heart and renew a right spirit.",
      wikiTerms: [],
    },
    {
      chapter: 52,
      title: "Why Boast in Evil?",
      summary: "Why do you boast in mischief?—God will destroy you forever—the righteous will see and fear—and laugh at the evildoer.",
      wikiTerms: [],
    },
    {
      chapter: 53,
      title: "The Fool",
      summary: "The fool says there is no God—corruption and abominable injustice—God looks to see if any understand.",
      wikiTerms: [],
    },
    {
      chapter: 54,
      title: "Save Me, O God",
      summary: "Save me by Your name—strangers rise against me—God is my helper; He repays my enemies.",
      wikiTerms: [],
    },
    {
      chapter: 55,
      title: "Cast Your Burden",
      summary: "Give ear to my complaint—if an enemy reproached me I could bear it—cast your burden on the Lord—He will sustain you.",
      wikiTerms: [],
    },
    {
      chapter: 56,
      title: "In God I Trust",
      summary: "Be merciful—when I am afraid I trust in God—what can flesh do?—His word I praise; I shall not be afraid.",
      wikiTerms: [],
    },
    {
      chapter: 57,
      title: "In the Shadow of Your Wings",
      summary: "Be merciful—my soul takes refuge under Your wings—God sends from heaven steadfast love and faithfulness.",
      wikiTerms: [],
    },
    {
      chapter: 58,
      title: "Do You Judge Uprightly?",
      summary: "Do you judge uprightly, O gods?—the wicked go astray from birth—let them melt like a snail—the righteous will rejoice.",
      wikiTerms: [],
    },
    {
      chapter: 59,
      title: "Deliver Me From Bloodguiltiness",
      summary: "Deliver me from my enemies—consume them in wrath—but I will sing of Your power morning by morning.",
      wikiTerms: [],
    },
    {
      chapter: 60,
      title: "You Have Rejected Us",
      summary: "You have made us stagger—yet You have given a banner—help with Your right hand—through God we shall do valiantly.",
      wikiTerms: [],
    },
    {
      chapter: 61,
      title: "Lead Me to the Rock",
      summary: "Hear my cry—lead me to the rock higher than I—for You have been my refuge—a strong tower against the enemy.",
      wikiTerms: [],
    },
    {
      chapter: 62,
      title: "My Soul Waits in Silence",
      summary: "My soul finds rest in God alone—He alone is my rock—power belongs to God; steadfast love is Yours.",
      wikiTerms: [],
    },
    {
      chapter: 63,
      title: "Thirsting for God",
      summary: "O God, You are my God—earnestly I seek You—as in a dry land my soul thirsts—Your steadfast love is better than life.",
      wikiTerms: [],
    },
    {
      chapter: 64,
      title: "Hide Me From Conspiracy",
      summary: "Hide me from secret plots—suddenly they shoot—God will shoot them—the righteous will glad in the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 65,
      title: "Praise Waits for You",
      summary: "Praise is silent for You in Zion—You answer prayer—You crown the year with bounty—the pastures drip with abundance.",
      wikiTerms: [],
    },
    {
      chapter: 66,
      title: "Come and See",
      summary: "Make a joyful noise—come and see God's deeds—He turned sea to dry land—we went through fire and water—You brought us out.",
      wikiTerms: [],
    },
    {
      chapter: 67,
      title: "God Be Merciful",
      summary: "God be merciful and bless us—let the earth yield her increase—God shall bless us; all ends shall fear Him.",
      wikiTerms: [],
    },
    {
      chapter: 68,
      title: "Let God Arise",
      summary: "Let God arise—His enemies scatter—He is Father of the fatherless—He leads out prisoners with singing—bless God in the great congregation.",
      wikiTerms: [],
    },
    {
      chapter: 69,
      title: "Waters Overflow Me",
      summary: "Save me, O God—waters come to my soul—I sink in deep mire—for Your sake I bear reproach—zeal for Your house consumes me.",
      wikiTerms: [],
    },
    {
      chapter: 70,
      title: "Make Haste, O God",
      summary: "Make haste to deliver me—let those who seek You rejoice—poor and needy, let them be glad in the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 71,
      title: "From Youth to Old Age",
      summary: "In You I trust from youth—cast me not off in old age—my mouth will tell of Your righteousness all day long.",
      wikiTerms: [],
    },
    {
      chapter: 72,
      title: "Pray for the King",
      summary: "Give the king Your justice—may he defend the poor—may righteousness flourish—may all nations call him blessed.",
      wikiTerms: [],
    },
    {
      chapter: 73,
      title: "Surely God Is Good",
      summary: "My feet had almost slipped seeing the wicked at ease—until I entered God's sanctuary—You guide me with Your counsel.",
      wikiTerms: [],
    },
    {
      chapter: 74,
      title: "Why Does Your Anger Smoke?",
      summary: "Why does Your anger smoke against Your sheep—the enemy roars in Your sanctuary—arise; remember Your covenant.",
      wikiTerms: [],
    },
    {
      chapter: 75,
      title: "We Give Thanks",
      summary: "We give thanks—Your wondrous deeds are our meditation—when the earth totters God holds its pillars firm—He judges uprightly.",
      wikiTerms: [],
    },
    {
      chapter: 76,
      title: "God Known in Judah",
      summary: "In Salem is His tabernacle—at His rebuke horse and rider fall—who can stand before You when You are angry?",
      wikiTerms: [],
    },
    {
      chapter: 77,
      title: "Has God Forgotten?",
      summary: "I cry to God—has He forgotten mercy?—I remember Your deeds of old—Your way is holy—You redeemed Your people.",
      wikiTerms: [],
    },
    {
      chapter: 78,
      title: "Tell the Coming Generation",
      summary: "Give ear, my people—open your mouth in parables—tell how God worked wonders yet they rebelled—He chose Zion and David.",
      wikiTerms: [],
    },
    {
      chapter: 79,
      title: "The Nations Invade",
      summary: "O God, the nations have invaded Your inheritance—pour out wrath—help us for Your name's sake—for the groans of the prisoner.",
      wikiTerms: [],
    },
    {
      chapter: 80,
      title: "Restore Us, O Shepherd",
      summary: "Give ear, Shepherd of Israel—restore us—let Your face shine—turn us again—let Your hand be with the man at Your right hand.",
      wikiTerms: [],
    },
    {
      chapter: 81,
      title: "Sing Aloud to God",
      summary: "Sing aloud—open wide your mouth—I am the Lord who brought you from Egypt—if only you had listened—You would feed on finest wheat.",
      wikiTerms: [],
    },
    {
      chapter: 82,
      title: "God Among the Gods",
      summary: "God stands in the divine council—judge the unjust—defend the weak and orphan—all the foundations are shaken.",
      wikiTerms: [],
    },
    {
      chapter: 83,
      title: "Keep Not Silence",
      summary: "O God, keep not silence—a confederacy plots against Your hidden ones—make them like whirling dust—let them know You alone are Most High.",
      wikiTerms: [],
    },
    {
      chapter: 84,
      title: "Lovely Are Your Tabernacles",
      summary: "How lovely Your dwelling—my soul longs—even sparrow finds a nest—blessed are those who dwell in Your house.",
      wikiTerms: [],
    },
    {
      chapter: 85,
      title: "Restore Us Again",
      summary: "You forgave the land—show us steadfast love—let lovingkindness and truth meet—righteousness and peace kiss.",
      wikiTerms: [],
    },
    {
      chapter: 86,
      title: "Bow Down, O Lord",
      summary: "Incline Your ear—You are good and forgiving—when I am in trouble I call—teach me Your way—great are Your works.",
      wikiTerms: [],
    },
    {
      chapter: 87,
      title: "On the Holy Mount",
      summary: "His foundation is on holy mountains—the Lord loves Zion's gates—of Zion it shall be said \"This one was born there.\"",
      wikiTerms: [],
    },
    {
      chapter: 88,
      title: "Darkness Is My Friend",
      summary: "Day and night I cry—my soul is full of trouble—You have put me in the lowest pit—darkness is my closest friend.",
      wikiTerms: [],
    },
    {
      chapter: 89,
      title: "Covenant With David",
      summary: "I will sing of the Lord's steadfast love forever—His covenant with David stands—though discipline comes, His faithfulness endures.",
      wikiTerms: [],
    },
    {
      chapter: 90,
      title: "Our Dwelling Place",
      summary: "Lord, You have been our dwelling place in all generations—our days are grass—teach us to number our days that we may gain wisdom.",
      wikiTerms: [],
    },
    {
      chapter: 91,
      title: "Shelter of the Most High",
      summary: "He who dwells in the shelter of the Most High abides under His shadow—He will deliver you—His angels charge over you.",
      wikiTerms: [],
    },
    {
      chapter: 92,
      title: "It Is Good to Give Thanks",
      summary: "It is good to give thanks—Your works are great—though the wicked sprout like grass they are destroyed forever—but You are exalted.",
      wikiTerms: [],
    },
    {
      chapter: 93,
      title: "The Lord Reigns",
      summary: "The Lord reigns—He is clothed with majesty—the world is established; the floods lift up their voices—the Lord on high is mighty.",
      wikiTerms: [],
    },
    {
      chapter: 94,
      title: "O Lord, God of Vengeance",
      summary: "Shall the throne of wickedness have fellowship with You?—He disciplines nations—blessed is the man You instruct—He will not forsake.",
      wikiTerms: [],
    },
    {
      chapter: 95,
      title: "O Come, Let Us Sing",
      summary: "O come, let us sing—let us kneel—He is our God—we are His people—do not harden your hearts as at Meribah.",
      wikiTerms: [],
    },
    {
      chapter: 96,
      title: "Sing to the Lord",
      summary: "Sing a new song—declare His salvation—worship in beauty—the Lord reigns—the heavens are glad—the sea roars.",
      wikiTerms: [],
    },
    {
      chapter: 97,
      title: "The Lord Reigns in Zion",
      summary: "The Lord reigns—clouds and thick darkness—fire goes before Him—light shines for the righteous—rejoice in the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 98,
      title: "Sing to the Lord a New Song",
      summary: "Sing—He has revealed salvation—make a joyful noise—let the sea roar—He comes to judge the earth with equity.",
      wikiTerms: [],
    },
    {
      chapter: 99,
      title: "The Lord Is Holy",
      summary: "The Lord reigns—let the peoples tremble—He sits between the cherubim—Moses and Aaron called on Him—He answered them.",
      wikiTerms: [],
    },
    {
      chapter: 100,
      title: "Enter With Thanksgiving",
      summary: "Make a joyful noise—serve with gladness—enter His gates with thanksgiving—know that the Lord is God—we are His people.",
      wikiTerms: [],
    },
    {
      chapter: 101,
      title: "Integrity in the House",
      summary: "I will walk with integrity—no perverse thing—who slanders secretly—I will not endure—daily I will cut off the wicked.",
      wikiTerms: [],
    },
    {
      chapter: 102,
      title: "Do Not Hide Your Face",
      summary: "Hear my prayer—do not hide in my days of smoke—You laid foundations—children yet unborn shall praise You when You build Zion.",
      wikiTerms: [],
    },
    {
      chapter: 103,
      title: "Bless the Lord, O My Soul",
      summary: "Bless the Lord—forget not His benefits—He forgives, heals, crowns—His steadfast love is high as the heavens.",
      wikiTerms: [],
    },
    {
      chapter: 104,
      title: "Bless the Lord, O My Soul",
      summary: "You stretch out the heavens—You make springs in valleys—You give wine, bread, oil—Leviathan plays—You renew the face of the ground.",
      wikiTerms: [],
    },
    {
      chapter: 105,
      title: "Remember His Marvelous Works",
      summary: "O give thanks—remember His wonders—He remembered His covenant with Abraham—Joseph, Israel in Egypt, plagues, Exodus.",
      wikiTerms: [],
    },
    {
      chapter: 106,
      title: "Praise Ye the Lord",
      summary: "Praise the Lord—His steadfast love endures—we have sinned like our fathers—yet He saved them for His name's sake—gather us from nations.",
      wikiTerms: [],
    },
    {
      chapter: 107,
      title: "Let the Redeemed Say So",
      summary: "Let the redeemed tell—He gathered from distress—some wandered—some sat in darkness—He satisfies the longing soul—He stills the storm.",
      wikiTerms: [],
    },
    {
      chapter: 108,
      title: "My Heart Is Fixed",
      summary: "My heart is fixed—awake my glory—I will praise among the nations—through God we shall do valiantly—He treads down our enemies.",
      wikiTerms: [],
    },
    {
      chapter: 109,
      title: "Hold Not Your Peace",
      summary: "Do not be silent—wicked accusers surround me—let curses return on their own head—but You, Lord, deal on my behalf for Your name.",
      wikiTerms: [],
    },
    {
      chapter: 110,
      title: "Sit at My Right Hand",
      summary: "The Lord says to my Lord—sit at My right hand—rule in midst of enemies—You are a priest forever—He will strike through kings.",
      wikiTerms: [],
    },
    {
      chapter: 111,
      title: "Great Are the Works of the Lord",
      summary: "I will praise with whole heart—His works are great—He provides food—He sent redemption—the fear of the Lord is wisdom.",
      wikiTerms: [],
    },
    {
      chapter: 112,
      title: "Blessed Is the Man",
      summary: "Blessed is the man who fears the Lord—wealth in his house—light rises in darkness—he is generous and steadfast—he will not be moved.",
      wikiTerms: [],
    },
    {
      chapter: 113,
      title: "From the Rising of the Sun",
      summary: "Praise the name of the Lord—He raises the poor from dust—He gives the barren a home—praise the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 114,
      title: "When Israel Went Out of Egypt",
      summary: "When Israel went out—the sea fled—Jordan turned back—tremble, earth, at the presence of the God of Jacob.",
      wikiTerms: [],
    },
    {
      chapter: 115,
      title: "Not to Us, O Lord",
      summary: "Not to us but to Your name—our God is in heaven—idols have mouths but cannot speak—those who fear the Lord trust Him.",
      wikiTerms: [],
    },
    {
      chapter: 116,
      title: "I Love the Lord",
      summary: "I love the Lord—He heard my voice—I will take the cup of salvation—precious in the Lord's sight is the death of His saints.",
      wikiTerms: [],
    },
    {
      chapter: 117,
      title: "Praise the Lord, All Nations",
      summary: "Praise the Lord, all nations—extol Him, all peoples—His steadfast love toward us is great—praise the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 118,
      title: "His Steadfast Love Endures",
      summary: "Give thanks—His steadfast love endures—I called in distress—He answered—the stone the builders rejected has become the cornerstone.",
      wikiTerms: [],
    },
    {
      chapter: 119,
      title: "Love of God's Word",
      summary: "Blessed are those who walk in the law—an acrostic meditation on commandments, statutes, and precepts—revive me according to Your word.",
      wikiTerms: [],
    },
    {
      chapter: 120,
      title: "In My Distress I Cried",
      summary: "In distress I cried—deliver me from lying lips—woe to me—I dwell among those who hate peace.",
      wikiTerms: [],
    },
    {
      chapter: 121,
      title: "My Help From the Hills",
      summary: "I lift my eyes to the hills—my help comes from the Lord who made heaven and earth—He will not slumber—He keeps your life.",
      wikiTerms: [],
    },
    {
      chapter: 122,
      title: "I Was Glad",
      summary: "I was glad when they said let us go to the house of the Lord—pray for Jerusalem's peace—there thrones for judgment stand.",
      wikiTerms: [],
    },
    {
      chapter: 123,
      title: "Eyes to the Lord",
      summary: "To You I lift my eyes—have mercy—as eyes of servants look to masters, so our eyes to the Lord our God.",
      wikiTerms: [],
    },
    {
      chapter: 124,
      title: "If It Had Not Been the Lord",
      summary: "If the Lord had not been on our side—when men rose against us—they would have swallowed us alive—blessed be the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 125,
      title: "Those Who Trust in the Lord",
      summary: "Those who trust in the Lord are like Mount Zion—peace be upon Israel—the scepter of wickedness shall not rest on the land.",
      wikiTerms: [],
    },
    {
      chapter: 126,
      title: "Restore Our Fortunes",
      summary: "When the Lord restored Zion we were like dreamers—those who sow in tears shall reap with shouts of joy—bring back our captivity.",
      wikiTerms: [],
    },
    {
      chapter: 127,
      title: "Unless the Lord Builds",
      summary: "Unless the Lord builds the house they labor in vain—children are a heritage—happy is the man whose quiver is full.",
      wikiTerms: [],
    },
    {
      chapter: 128,
      title: "Blessed Is Everyone Who Fears the Lord",
      summary: "Blessed is everyone who fears the Lord—your wife like a fruitful vine—your children like olive shoots around your table.",
      wikiTerms: [],
    },
    {
      chapter: 129,
      title: "They Have Afflicted Me",
      summary: "Many times they afflicted Israel from youth—yet they have not prevailed—the wicked shall be cut off—let all who hate Zion be put to shame.",
      wikiTerms: [],
    },
    {
      chapter: 130,
      title: "Out of the Depths",
      summary: "Out of the depths I cry—if You marked iniquities who could stand?—with the Lord is steadfast love—Israel hope in the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 131,
      title: "Like a Weaned Child",
      summary: "I do not occupy myself with things too great—I have calmed my soul like a weaned child—O Israel hope in the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 132,
      title: "Remember David",
      summary: "Remember David's affliction—how he swore to find a dwelling for the Ark—Zion is God's resting place forever—He will bless her poor.",
      wikiTerms: [],
    },
    {
      chapter: 133,
      title: "How Good and Pleasant",
      summary: "How good when brothers dwell in unity—it is like oil on Aaron's beard—dew of Hermon—there the Lord commands blessing forever.",
      wikiTerms: [],
    },
    {
      chapter: 134,
      title: "Bless the Lord at Night",
      summary: "Bless the Lord, all servants who stand by night—lift hands—may the Lord bless you from Zion—Maker of heaven and earth.",
      wikiTerms: [],
    },
    {
      chapter: 135,
      title: "Praise Ye the Name of the Lord",
      summary: "Praise the Lord—He is good—He struck down kings—He gave Israel their land—idols are silver and gold—the Lord bless His people.",
      wikiTerms: [],
    },
    {
      chapter: 136,
      title: "His Steadfast Love Endures Forever",
      summary: "Give thanks—for His steadfast love endures—He alone does wonders—He brought Israel through the sea—He remembers us—thank the God of heaven.",
      wikiTerms: [],
    },
    {
      chapter: 137,
      title: "By the Rivers of Babylon",
      summary: "By Babylon's rivers we wept—our tormentors demanded songs—if I forget Jerusalem let my right hand forget—remember Edom's day.",
      wikiTerms: [],
    },
    {
      chapter: 138,
      title: "I Give You Thanks With My Whole Heart",
      summary: "I give thanks before the gods—You have exalted Your name—when I walk in trouble You revive me—the Lord will fulfill His purpose for me.",
      wikiTerms: [],
    },
    {
      chapter: 139,
      title: "Search Me, O God",
      summary: "You have searched me—where can I flee?—if I take wings—Your hand leads—see if wicked way is in me—lead in everlasting way.",
      wikiTerms: [],
    },
    {
      chapter: 140,
      title: "Deliver Me, O Lord",
      summary: "Deliver me from evil men—let burning coals fall on them—I know the Lord maintains the cause of the afflicted—let the righteous praise.",
      wikiTerms: [],
    },
    {
      chapter: 141,
      title: "Let My Prayer Be Counted as Incense",
      summary: "Let my prayer rise as incense—set a guard on my mouth—keep me from the dainties of the wicked—let the righteous strike me in kindness.",
      wikiTerms: [],
    },
    {
      chapter: 142,
      title: "I Cry With My Voice",
      summary: "I cry with my voice to the Lord—no one cares—You are my refuge—bring me out—then the righteous will gather to me.",
      wikiTerms: [],
    },
    {
      chapter: 143,
      title: "Cause Me to Hear Your Lovingkindness",
      summary: "Do not enter judgment—enemy crushes me—cause me to hear mercy—teach me to do Your will—revive me—let Your good Spirit lead.",
      wikiTerms: [],
    },
    {
      chapter: 144,
      title: "Blessed Be the Lord My Rock",
      summary: "Blessed be the Lord—my hands teach war—may our sons be like plants—may our daughters be corner pillars—happy the people whose God is the Lord.",
      wikiTerms: [],
    },
    {
      chapter: 145,
      title: "I Will Extol You, My God",
      summary: "I will extol You—every day bless You—great is the Lord—He upholds the falling—He satisfies every living thing—His kingdom endures.",
      wikiTerms: [],
    },
    {
      chapter: 146,
      title: "Put Not Your Trust in Princes",
      summary: "Do not trust princes—happy is he whose help is the God of Jacob—He keeps faith—He sets prisoners free—the Lord shall reign forever.",
      wikiTerms: [],
    },
    {
      chapter: 147,
      title: "He Heals the Brokenhearted",
      summary: "Praise—He heals the brokenhearted—He counts stars—He sends snow—He has no pleasure in horse strength—He delights in those who fear Him.",
      wikiTerms: [],
    },
    {
      chapter: 148,
      title: "Praise From All Creation",
      summary: "Praise from heavens, waters, sun, moon, deeps, fire, hills, trees, beasts, kings—He has raised a horn for His people.",
      wikiTerms: [],
    },
    {
      chapter: 149,
      title: "Sing to the Lord a New Song",
      summary: "Sing in the assembly—Israel rejoices in its Maker—high praises in throat—two-edged sword in hand—this honor is for all His saints.",
      wikiTerms: [],
    },
    {
      chapter: 150,
      title: "Let Everything Praise the Lord",
      summary: "Praise God in sanctuary—praise for mighty deeds—praise with trumpet, harp, dance, strings, cymbals—let everything that breathes praise the Lord.",
      wikiTerms: [],
    },
  ],
});
ALL_BOOKS.push({
  title: "Proverbs",
  shortTitle: "Proverbs",
  apiBook: "proverbs",
  section: "poetry",
  chapters: 31,
  pages: [
    {
      chapter: 1,
      title: "Purpose of Proverbs",
      summary: "The fear of the Lord is the beginning of knowledge; wisdom calls in the streets against scoffers and simple ones.",
      wikiTerms: [],
    },
    {
      chapter: 2,
      title: "Seeking Wisdom",
      summary: "Seek wisdom like silver and you will understand the fear of the Lord and find knowledge of God.",
      wikiTerms: [],
    },
    {
      chapter: 3,
      title: "Trust the Lord",
      summary: "Trust the Lord with all your heart; honor Him with wealth; wisdom is a tree of life—do not despise discipline.",
      wikiTerms: [],
    },
    {
      chapter: 4,
      title: "Hold Fast Instruction",
      summary: "Fathers urge sons to cling to wisdom's path—avoid the wicked path and the evil whose sleep is robbed without bread.",
      wikiTerms: [],
    },
    {
      chapter: 5,
      title: "Warning Against Adultery",
      summary: "Rejoice in your own spouse; the strange woman's lips drip honey but her end is bitter as wormwood and sharp as a sword.",
      wikiTerms: [],
    },
    {
      chapter: 6,
      title: "Practical Warnings",
      summary: "Warnings on surety for a neighbor, sloth, and seven things the Lord hates—including lying tongue and sowing discord.",
      wikiTerms: [],
    },
    {
      chapter: 7,
      title: "The Seduction Scene",
      summary: "A naive youth follows the adulteress to her house—her house is the way to death and the chambers to the dead.",
      wikiTerms: [],
    },
    {
      chapter: 8,
      title: "Wisdom Calls",
      summary: "Wisdom personified calls in the heights—by wisdom kings reign; blessed are those who find her before silver and gold.",
      wikiTerms: [],
    },
    {
      chapter: 9,
      title: "Two Banquets",
      summary: "Wisdom builds her house; Folly also calls from her doorway—simple ones turn in to death, but the fear of the Lord is life.",
      wikiTerms: [],
    },
    {
      chapter: 10,
      title: "Righteous and Wicked Contrasts",
      summary: "A chain of proverbs contrasts the righteous mouth, diligent hand, and integrity with the wicked, violent, and perishing.",
      wikiTerms: [],
    },
    {
      chapter: 11,
      title: "Integrity and Generosity",
      summary: "Honest scales, generous giving, and humility bring life; trust in riches fails and the cruelly treacherous are destroyed.",
      wikiTerms: [],
    },
    {
      chapter: 12,
      title: "Speech and Work",
      summary: "Truthful lips endure; diligent hands rule; rash words are like sword thrusts; the prudent ignore insults.",
      wikiTerms: [],
    },
    {
      chapter: 13,
      title: "Discipline and Wealth",
      summary: "A wise son hears correction; the sluggard craves but has nothing; wealth gained hastily dwindles—righteousness brings life.",
      wikiTerms: [],
    },
    {
      chapter: 14,
      title: "Ways of Wisdom and Folly",
      summary: "The upright fear the Lord; a quick temper acts foolishly; the prudent are crowned with knowledge; the wicked sink in evil.",
      wikiTerms: [],
    },
    {
      chapter: 15,
      title: "Gentle Tongue and Fear of God",
      summary: "A soft answer turns away wrath; God's eyes are everywhere; a cheerful heart is good medicine; the righteous seeks knowledge.",
      wikiTerms: [],
    },
    {
      chapter: 16,
      title: "The Lord Directs Steps",
      summary: "Commit your work to the Lord; pride goes before destruction; gray hair is a crown; a whisperer separates friends.",
      wikiTerms: [],
    },
    {
      chapter: 17,
      title: "Peace and Folly",
      summary: "Better a dry crust with peace than a house full of feasting with strife; a friend loves at all times; a joyful heart does good.",
      wikiTerms: [],
    },
    {
      chapter: 18,
      title: "The Power of Words",
      summary: "The tongue has power of life and death; the rich man's wealth is his strong city; a brother offended is harder than a city.",
      wikiTerms: [],
    },
    {
      chapter: 19,
      title: "Kindness and Laziness",
      summary: "Kindness to the poor lends to the Lord; a sluggard buries his hand in the dish; discipline drives folly far away.",
      wikiTerms: [],
    },
    {
      chapter: 20,
      title: "Wine and Kings",
      summary: "Wine is a mocker; a king's glory is to search out a matter; who can say \"I have made my heart pure\"?—honest weights please God.",
      wikiTerms: [],
    },
    {
      chapter: 21,
      title: "Just Scales and Justice",
      summary: "The king's heart is channels in God's hand; justice brings joy to the righteous; a false witness will perish.",
      wikiTerms: [],
    },
    {
      chapter: 22,
      title: "Train Up a Child",
      summary: "A good name is better than riches; train a child in the way he should go; the rich rule the poor—borrower is slave to lender.",
      wikiTerms: [],
    },
    {
      chapter: 23,
      title: "Do Not Envy Sinners",
      summary: "Do not fret over sinners' wealth; apply your heart to wisdom; excess wine and gluttony bring poverty and wounds.",
      wikiTerms: [],
    },
    {
      chapter: 24,
      title: "Do Not Join Wicked Plots",
      summary: "Do not envy wicked men; wisdom builds a house; a just man may fall seven times and rise—God does not delight in evil schemes.",
      wikiTerms: [],
    },
    {
      chapter: 25,
      title: "Proverbs of Solomon Copied",
      summary: "It is God's glory to conceal a matter; soft tongue breaks bone; heap coals on an enemy's head by kindness; a brawling wife is relentless drops.",
      wikiTerms: [],
    },
    {
      chapter: 26,
      title: "Fools and Sluggards",
      summary: "Honor is not fitting for a fool; a sluggard is wiser in his own eyes than seven who answer discreetly—avoid quarrels not yours.",
      wikiTerms: [],
    },
    {
      chapter: 27,
      title: "Boasting About Tomorrow",
      summary: "Do not boast about tomorrow; let another praise you; iron sharpens iron; the crucible tests silver and a friend tests a face.",
      wikiTerms: [],
    },
    {
      chapter: 28,
      title: "Wicked Flee None Pursuing",
      summary: "The wicked flee when no one pursues; the faithful confess sin; a stingy man hastens after wealth but lacks understanding.",
      wikiTerms: [],
    },
    {
      chapter: 29,
      title: "When the Wicked Rule",
      summary: "When the wicked rule the people groan; a child left to himself shames his mother; the righteous care for justice for the poor.",
      wikiTerms: [],
    },
    {
      chapter: 30,
      title: "The Words of Agur",
      summary: "Agur confesses ignorance before God, lists things never satisfied, things too wonderful, and small yet wise creatures.",
      wikiTerms: [],
    },
    {
      chapter: 31,
      title: "Lemuel and the Virtuous Woman",
      summary: "Lemuel's mother warns against women and strong drink; the chapter closes with an acrostic praising a wife of noble character who fears the Lord.",
      wikiTerms: [],
    },
  ],
});
ALL_BOOKS.push({
  title: "Ecclesiastes",
  shortTitle: "Ecclesiastes",
  apiBook: "ecclesiastes",
  section: "poetry",
  chapters: 12,
  pages: [
    {
      chapter: 1,
      title: "All Is Vanity",
      summary: "The Preacher declares all is vapor under the sun—wisdom, toil, and gain—and surveys the endless cycle of generations.",
      wikiTerms: [],
    },
    {
      chapter: 2,
      title: "Pleasure and Toil",
      summary: "He tests pleasure, laughter, great works, and wisdom, and finds them all empty when grasped as ultimate gain.",
      wikiTerms: [],
    },
    {
      chapter: 3,
      title: "A Time for Everything",
      summary: "There is a season for birth and death, planting and uprooting, weeping and dancing—God has made everything beautiful in its time.",
      wikiTerms: [],
    },
    {
      chapter: 4,
      title: "Oppression and Friendship",
      summary: "He sees oppression and envy's vanity, yet a companion in toil is better than standing alone in meaningless striving.",
      wikiTerms: [],
    },
    {
      chapter: 5,
      title: "Reverence Before God",
      summary: "Guard your steps in God's house; pay vows; do not let money corrupt dreams—God alone gives enjoyment as gift.",
      wikiTerms: [],
    },
    {
      chapter: 6,
      title: "Riches Without Enjoyment",
      summary: "A man may have riches and long life yet never enjoy them—this the Preacher calls an evil sickness.",
      wikiTerms: [],
    },
    {
      chapter: 7,
      title: "The Value of Sorrow",
      summary: "A good name, the day of death, and the house of mourning can teach more than empty laughter in the house of feasting.",
      wikiTerms: [],
    },
    {
      chapter: 8,
      title: "Authority and Mystery",
      summary: "Respect the king's command yet know the righteous may suffer and the wicked prosper—for God brings all to judgment.",
      wikiTerms: [],
    },
    {
      chapter: 9,
      title: "Common Fate and Joy",
      summary: "All share one fate; enjoy life with the wife you love and your bread with a merry heart while God gives breath.",
      wikiTerms: [],
    },
    {
      chapter: 10,
      title: "Folly in High Places",
      summary: "Dead flies spoil perfume—little folly can outweigh wisdom; the fool is lifted while the rich sit low—beware a city's rulers.",
      wikiTerms: [],
    },
    {
      chapter: 11,
      title: "Cast Your Bread",
      summary: "Give generously and sow widely—you do not know which effort will prosper; rejoice in youth yet know God will bring every deed to judgment.",
      wikiTerms: [],
    },
    {
      chapter: 12,
      title: "Remember Your Creator",
      summary: "Remember God in the days of youth before age and death's darkening poem; fear God and keep His commands—this is the whole duty of humankind.",
      wikiTerms: [],
    },
  ],
});
ALL_BOOKS.push({
  title: "Song of Solomon",
  shortTitle: "Song",
  apiBook: "song of solomon",
  section: "poetry",
  chapters: 8,
  pages: [
    {
      chapter: 1,
      title: "Longing and Fragrance",
      summary: "The Song opens with the bride's desire for kisses and the king's love; daughters of Jerusalem are called to behold Solomon's banner of love.",
      wikiTerms: [],
    },
    {
      chapter: 2,
      title: "Spring and the Foxes",
      summary: "Lovers rejoice in spring; the bridegroom calls his love a lily among thorns and asks the foxes that spoil vineyards to be caught.",
      wikiTerms: [],
    },
    {
      chapter: 3,
      title: "Seeking and the Procession",
      summary: "By night on the city bed the bride seeks her beloved; a royal litter and Solomon with his crown appear in gladness.",
      wikiTerms: [],
    },
    {
      chapter: 4,
      title: "The Bridegroom's Praise",
      summary: "He praises her eyes, hair, teeth, lips, neck, and garden—she invites him to come into the garden of delights.",
      wikiTerms: [],
    },
    {
      chapter: 5,
      title: "The Bride Seeks Him",
      summary: "She opens too late; she seeks him in the streets; companions ask what is special about him—she paints his radiant majesty.",
      wikiTerms: [],
    },
    {
      chapter: 6,
      title: "Praise at Mahanaim",
      summary: "The beloved praises her beauty as lovely as Tirzah; royal imagery and dance celebrate their love at peace.",
      wikiTerms: [],
    },
    {
      chapter: 7,
      title: "Dance of Love",
      summary: "He praises her feet, hips, navel, and neck; love's embrace is described with vineyard and fruit imagery of delight.",
      wikiTerms: [],
    },
    {
      chapter: 8,
      title: "Love Strong as Death",
      summary: "Love is sealed; jealousy is cruel as the grave; Solomon's vineyard and the bride's own vineyard close with enduring passion and devotion.",
      wikiTerms: [],
    },
  ],
});
