// ─── Genesis — All 50 Chapters ───
// Each chapter: TLDR summary + wiki term links
// Full verse text is fetched from bible-api.com and cached locally

ALL_BOOKS.push({
  title: "Genesis",
  shortTitle: "Genesis",
  apiBook: "genesis",
  section: "law",
  chapters: 50,
  pages: [
    {
      chapter: 1,
      title: "The Creation",
      summary: "God creates the heavens and the earth in six days — light, sky, land, sun and moon, sea creatures and birds, animals, and finally humanity, made in His own image. On seeing everything He made, He calls it very good.",
      wikiTerms: [
        { phrase: "God created", id: "creation" },
        { phrase: "the heaven and the earth", id: "creation" },
        { phrase: "in our image", id: "image-of-god" },
        { phrase: "man", id: "adam" },
      ],
    },
    {
      chapter: 2,
      title: "The Garden of Eden",
      summary: "God rests on the seventh day. He forms Adam from dust, breathes life into him, and places him in Eden — a paradise with a river, fruit trees, and one forbidden tree. Finding that Adam needs a partner, God creates Eve from his rib.",
      wikiTerms: [
        { phrase: "Adam", id: "adam" },
        { phrase: "Eden", id: "eden" },
        { phrase: "the tree of knowledge", id: "tree-of-knowledge" },
        { phrase: "rib", id: "eve" },
      ],
    },
    {
      chapter: 3,
      title: "The Fall",
      summary: "The serpent convinces Eve to eat from the forbidden tree. She shares it with Adam. Their innocence shatters — they feel shame, hide from God, and blame each other. God curses the serpent, promises pain in childbirth and toil in the ground, and banishes them from Eden forever.",
      wikiTerms: [
        { phrase: "serpent", id: "the-serpent" },
        { phrase: "Eve", id: "eve" },
        { phrase: "Adam", id: "adam" },
        { phrase: "Eden", id: "eden" },
      ],
    },
    {
      chapter: 4,
      title: "Cain and Abel",
      summary: "Adam and Eve's sons bring offerings to God. Abel's is accepted; Cain's is not. Consumed by jealousy, Cain murders his brother in the field — the first killing in human history. God curses Cain to wander the earth but marks him for protection. Cain builds the first city.",
      wikiTerms: [
        { phrase: "Cain", id: "cain" },
        { phrase: "Abel", id: "abel" },
        { phrase: "Eve", id: "eve" },
        { phrase: "Adam", id: "adam" },
      ],
    },
    {
      chapter: 5,
      title: "From Adam to Noah",
      summary: "A genealogy stretching ten generations from Adam to Noah. Lifespans are enormous — Adam lives 930 years, Methuselah 969. One figure stands out: Enoch, who \"walked with God\" and was taken by God without dying. The chapter ends with Noah fathering Shem, Ham, and Japheth.",
      wikiTerms: [
        { phrase: "Adam", id: "adam" },
        { phrase: "Methuselah", id: "methuselah" },
        { phrase: "Enoch", id: "enoch" },
        { phrase: "Noah", id: "noah" },
      ],
    },
    {
      chapter: 6,
      title: "Corruption and the Ark",
      summary: "Humanity has become so wicked that God regrets creating them and resolves to destroy all life with a flood. But one man — Noah — finds favor in God's eyes. God instructs Noah to build an enormous ark and gives him exact dimensions. He is to bring his family and pairs of every animal aboard.",
      wikiTerms: [
        { phrase: "Noah", id: "noah" },
        { phrase: "ark", id: "the-ark" },
        { phrase: "Nephilim", id: "nephilim" },
      ],
    },
    {
      chapter: 7,
      title: "The Flood",
      summary: "Noah, his family, and the animals enter the ark. God shuts the door. Rain falls for forty days and nights. The waters rise until every mountain is covered and all life outside the ark is destroyed. The waters prevail on the earth for 150 days.",
      wikiTerms: [
        { phrase: "Noah", id: "noah" },
        { phrase: "ark", id: "the-ark" },
        { phrase: "forty days", id: "the-flood" },
      ],
    },
    {
      chapter: 8,
      title: "The Waters Recede",
      summary: "God sends a wind over the earth and the waters begin to recede. The ark comes to rest on the mountains of Ararat. Noah sends out a raven, then a dove — which returns with an olive branch. When the ground is finally dry, God tells Noah to leave the ark. Noah builds an altar and makes an offering.",
      wikiTerms: [
        { phrase: "Noah", id: "noah" },
        { phrase: "Ararat", id: "ararat" },
        { phrase: "dove", id: "the-flood" },
      ],
    },
    {
      chapter: 9,
      title: "God's Covenant with Noah",
      summary: "God blesses Noah and establishes a covenant: never again will a flood destroy all life. The rainbow is set in the sky as the sign of this promise. Noah plants a vineyard, gets drunk, and is seen naked by his son Ham. Noah curses Ham's son Canaan and blesses Shem and Japheth.",
      wikiTerms: [
        { phrase: "Noah", id: "noah" },
        { phrase: "covenant", id: "covenant" },
        { phrase: "rainbow", id: "the-flood" },
        { phrase: "Ham", id: "ham" },
        { phrase: "Canaan", id: "canaan-person" },
      ],
    },
    {
      chapter: 10,
      title: "The Table of Nations",
      summary: "The descendants of Noah's three sons — Shem, Ham, and Japheth — spread out and become the nations of the ancient world. This chapter is a sweeping genealogy tracing how all the peoples known to the ancient Israelites originated from one family after the flood.",
      wikiTerms: [
        { phrase: "Shem", id: "shem" },
        { phrase: "Ham", id: "ham" },
        { phrase: "Japheth", id: "japheth" },
        { phrase: "Nimrod", id: "nimrod" },
      ],
    },
    {
      chapter: 11,
      title: "The Tower of Babel",
      summary: "Humanity, speaking one language, builds a city and a tower reaching to the heavens — a monument to self-sufficiency. God confuses their language and scatters them across the earth. The chapter then traces a genealogy from Shem down to Abram, setting the stage for the rest of the Bible.",
      wikiTerms: [
        { phrase: "Babel", id: "tower-of-babel" },
        { phrase: "Abram", id: "abraham" },
        { phrase: "Shem", id: "shem" },
      ],
    },
    {
      chapter: 12,
      title: "The Call of Abram",
      summary: "God tells Abram to leave his homeland and go to an unknown land, promising to make him a great nation and to bless all families of the earth through him. Abram obeys, traveling to Canaan. When famine hits, he goes to Egypt, where he passes off his wife Sarai as his sister to protect himself.",
      wikiTerms: [
        { phrase: "Abram", id: "abraham" },
        { phrase: "Sarai", id: "sarah" },
        { phrase: "Canaan", id: "canaan" },
        { phrase: "Egypt", id: "egypt" },
      ],
    },
    {
      chapter: 13,
      title: "Abram and Lot Separate",
      summary: "Abram and his nephew Lot have grown so wealthy that the land can't support them both. They agree to part ways. Lot chooses the lush Jordan valley near Sodom. God renews His promise to Abram: all the land he can see will belong to his descendants, who will be as numerous as dust.",
      wikiTerms: [
        { phrase: "Abram", id: "abraham" },
        { phrase: "Lot", id: "lot" },
        { phrase: "Sodom", id: "sodom" },
      ],
    },
    {
      chapter: 14,
      title: "War of the Kings",
      summary: "Four eastern kings defeat five local kings and carry off the people of Sodom — including Lot. Abram assembles 318 trained men, pursues the invaders, and rescues everyone. On his return, the mysterious priest-king Melchizedek blesses Abram, and Abram gives him a tenth of everything.",
      wikiTerms: [
        { phrase: "Abram", id: "abraham" },
        { phrase: "Lot", id: "lot" },
        { phrase: "Melchizedek", id: "melchizedek" },
        { phrase: "Sodom", id: "sodom" },
      ],
    },
    {
      chapter: 15,
      title: "The Covenant of the Stars",
      summary: "Abram asks God how His promises can come true when he has no children. God takes him outside and tells him to count the stars — that's how many descendants he'll have. Abram believes, and God counts it as righteousness. God then makes a solemn covenant, foretelling 400 years of slavery before deliverance.",
      wikiTerms: [
        { phrase: "Abram", id: "abraham" },
        { phrase: "covenant", id: "covenant" },
        { phrase: "righteousness", id: "righteousness" },
      ],
    },
    {
      chapter: 16,
      title: "Hagar and Ishmael",
      summary: "Sarai, still childless after years of waiting, gives her servant Hagar to Abram as a wife. Hagar conceives and begins to look down on Sarai. Sarai treats her harshly, and Hagar flees into the wilderness. An angel finds her and tells her to return — her son Ishmael will father a great nation.",
      wikiTerms: [
        { phrase: "Sarai", id: "sarah" },
        { phrase: "Hagar", id: "hagar" },
        { phrase: "Abram", id: "abraham" },
        { phrase: "Ishmael", id: "ishmael" },
      ],
    },
    {
      chapter: 17,
      title: "Circumcision and New Names",
      summary: "When Abram is 99, God appears and establishes an everlasting covenant. Abram becomes Abraham (\"father of many nations\") and Sarai becomes Sarah. Circumcision is given as the sign of the covenant. God promises that Sarah — at age 90 — will bear a son named Isaac. Abraham laughs.",
      wikiTerms: [
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Sarah", id: "sarah" },
        { phrase: "circumcision", id: "circumcision" },
        { phrase: "Isaac", id: "isaac" },
        { phrase: "covenant", id: "covenant" },
      ],
    },
    {
      chapter: 18,
      title: "Three Visitors at Mamre",
      summary: "Three mysterious visitors appear at Abraham's tent. He rushes to serve them a meal. They announce that Sarah will have a son within the year — she laughs from inside the tent. Then God reveals He is about to judge Sodom, and Abraham bargains with Him: will you destroy it if fifty righteous people live there? Forty? Ten?",
      wikiTerms: [
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Sarah", id: "sarah" },
        { phrase: "Sodom", id: "sodom" },
      ],
    },
    {
      chapter: 19,
      title: "Sodom and Gomorrah",
      summary: "Two angels arrive in Sodom. The men of the city surround Lot's house demanding the visitors. The angels strike the mob blind, warn Lot to flee, and rain fire and brimstone from heaven. Sodom and Gomorrah are annihilated. Lot's wife looks back and becomes a pillar of salt. Lot's daughters, believing they're the last people alive, get their father drunk.",
      wikiTerms: [
        { phrase: "Sodom", id: "sodom" },
        { phrase: "Lot", id: "lot" },
        { phrase: "Gomorrah", id: "sodom" },
      ],
    },
    {
      chapter: 20,
      title: "Abraham and Abimelech",
      summary: "Abraham moves south and again tells a local king — Abimelech of Gerar — that Sarah is his sister. God comes to Abimelech in a dream and warns him. Abimelech confronts Abraham, who admits the half-truth. The king sends them away with gifts and an open invitation to settle in his land.",
      wikiTerms: [
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Abimelech", id: "abimelech" },
        { phrase: "Sarah", id: "sarah" },
      ],
    },
    {
      chapter: 21,
      title: "Isaac Is Born",
      summary: "Sarah conceives and bears Isaac, just as God promised. She laughs with joy. But tension grows between Sarah and Hagar, and Sarah demands that Hagar and Ishmael be sent away. God tells Abraham to listen to Sarah, promising to make Ishmael a nation too. Hagar and the boy wander in the desert until God opens her eyes to a well.",
      wikiTerms: [
        { phrase: "Isaac", id: "isaac" },
        { phrase: "Sarah", id: "sarah" },
        { phrase: "Hagar", id: "hagar" },
        { phrase: "Ishmael", id: "ishmael" },
        { phrase: "Abraham", id: "abraham" },
      ],
    },
    {
      chapter: 22,
      title: "The Binding of Isaac",
      summary: "God tests Abraham with the most devastating command: sacrifice your only son Isaac as a burnt offering. Abraham obeys, traveling three days to Mount Moriah. He binds Isaac on the altar and raises the knife — but an angel stops him at the last instant. A ram caught in a thicket becomes the sacrifice instead. God reaffirms His covenant.",
      wikiTerms: [
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Isaac", id: "isaac" },
        { phrase: "Moriah", id: "moriah" },
        { phrase: "covenant", id: "covenant" },
      ],
    },
    {
      chapter: 23,
      title: "Sarah's Death",
      summary: "Sarah dies at 127 in Hebron. Abraham mourns her and negotiates with the Hittites to buy the cave of Machpelah as a burial place. He insists on paying full price — 400 shekels of silver. It becomes the first piece of the Promised Land that Abraham actually owns.",
      wikiTerms: [
        { phrase: "Sarah", id: "sarah" },
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Hebron", id: "hebron" },
        { phrase: "Machpelah", id: "machpelah" },
      ],
    },
    {
      chapter: 24,
      title: "A Bride for Isaac",
      summary: "Abraham sends his oldest servant back to Mesopotamia to find a wife for Isaac. The servant prays for a sign at a well — the woman who offers water to him and his camels will be the one. Rebekah appears and does exactly that. Her family consents, she travels to Canaan, and Isaac loves her.",
      wikiTerms: [
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Isaac", id: "isaac" },
        { phrase: "Rebekah", id: "rebekah" },
      ],
    },
    {
      chapter: 25,
      title: "Twins and a Birthright",
      summary: "Abraham remarries, has more children, and dies at 175 — buried beside Sarah at Machpelah. Isaac and Rebekah have twin sons: Esau (the outdoorsman) and Jacob (the quiet schemer). The two struggle even in the womb. One day Esau, famished, sells his birthright to Jacob for a bowl of red stew.",
      wikiTerms: [
        { phrase: "Abraham", id: "abraham" },
        { phrase: "Isaac", id: "isaac" },
        { phrase: "Esau", id: "esau" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "birthright", id: "birthright" },
      ],
    },
    {
      chapter: 26,
      title: "Isaac and the Wells",
      summary: "Famine drives Isaac to Gerar. God appears and renews the Abrahamic promises with him. Isaac, like his father, lies about his wife. He grows enormously wealthy, provoking jealousy — the Philistines fill in his wells. Isaac keeps digging new ones until he finds peace at Beersheba, where Abimelech comes to make a treaty.",
      wikiTerms: [
        { phrase: "Isaac", id: "isaac" },
        { phrase: "Rebekah", id: "rebekah" },
        { phrase: "Abimelech", id: "abimelech" },
        { phrase: "Beersheba", id: "beersheba" },
      ],
    },
    {
      chapter: 27,
      title: "The Stolen Blessing",
      summary: "Isaac, old and blind, prepares to give his deathbed blessing to Esau. But Rebekah orchestrates a scheme: Jacob puts on goatskins, brings fake stew, and deceives his father into blessing him instead. When Esau returns and discovers the theft, he weeps bitterly and vows to kill Jacob. Rebekah sends Jacob away to her brother Laban.",
      wikiTerms: [
        { phrase: "Isaac", id: "isaac" },
        { phrase: "Esau", id: "esau" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Rebekah", id: "rebekah" },
        { phrase: "Laban", id: "laban" },
      ],
    },
    {
      chapter: 28,
      title: "Jacob's Ladder",
      summary: "Fleeing to Haran, Jacob stops for the night and uses a stone as a pillow. He dreams of a stairway reaching to heaven with angels ascending and descending. God stands above it and repeats the promises made to Abraham and Isaac. Jacob wakes, names the place Bethel (\"house of God\"), and makes a vow.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Bethel", id: "bethel" },
        { phrase: "angels", id: "jacobs-ladder" },
      ],
    },
    {
      chapter: 29,
      title: "Jacob, Leah, and Rachel",
      summary: "Jacob arrives in Haran and meets Rachel at a well — he's so moved he weeps and kisses her. He agrees to work seven years for her hand in marriage, which \"seemed to him but a few days, for the love he had to her.\" But on the wedding night, Laban switches Rachel for her older sister Leah. Jacob works another seven years for Rachel.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Rachel", id: "rachel" },
        { phrase: "Leah", id: "leah" },
        { phrase: "Laban", id: "laban" },
      ],
    },
    {
      chapter: 30,
      title: "Children and Flocks",
      summary: "A fierce rivalry between Leah and Rachel drives the birth of Jacob's children. Leah bears son after son; Rachel, barren and desperate, gives her servant to Jacob. Eventually Rachel herself conceives Joseph. Meanwhile, Jacob negotiates with Laban for wages — using a clever breeding strategy, he builds enormous flocks of his own.",
      wikiTerms: [
        { phrase: "Leah", id: "leah" },
        { phrase: "Rachel", id: "rachel" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Laban", id: "laban" },
      ],
    },
    {
      chapter: 31,
      title: "Jacob Flees from Laban",
      summary: "After twenty years, God tells Jacob to return home. Jacob gathers his wives, children, and flocks and slips away while Laban is shearing sheep. Laban pursues him for seven days. God warns Laban in a dream not to harm Jacob. They confront each other, air their grievances, and finally make a peace covenant with a heap of stones.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Laban", id: "laban" },
        { phrase: "Rachel", id: "rachel" },
      ],
    },
    {
      chapter: 32,
      title: "Wrestling with God",
      summary: "Jacob sends messengers ahead to Esau and learns his brother is coming with 400 men. Terrified, he divides his camp, prays desperately, and sends lavish gifts ahead. That night, alone at the Jabbok river, he wrestles a mysterious figure until dawn. The figure dislocates Jacob's hip but cannot overpower him. Jacob is renamed Israel — \"he who struggles with God.\"",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Esau", id: "esau" },
        { phrase: "Israel", id: "jacob" },
        { phrase: "Jabbok", id: "jacob-wrestling" },
      ],
    },
    {
      chapter: 33,
      title: "Reunion with Esau",
      summary: "Jacob limps toward Esau, bowing seven times. But Esau runs to meet him, embraces him, and weeps. The brothers are reconciled. Esau returns to Seir; Jacob settles near Shechem and buys a plot of land, erecting an altar he calls \"God, the God of Israel.\"",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Esau", id: "esau" },
        { phrase: "Shechem", id: "shechem" },
      ],
    },
    {
      chapter: 34,
      title: "The Tragedy at Shechem",
      summary: "Dinah, Jacob's daughter, is raped by Shechem the prince. He falls in love with her and asks to marry her. Jacob's sons agree to the marriage on one condition — all the men of Shechem must be circumcised. While they're recovering, Simeon and Levi slaughter every man in the city and rescue Dinah. Jacob is horrified.",
      wikiTerms: [
        { phrase: "Dinah", id: "dinah" },
        { phrase: "Simeon", id: "simeon" },
        { phrase: "Levi", id: "levi" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Shechem", id: "shechem" },
      ],
    },
    {
      chapter: 35,
      title: "Return to Bethel",
      summary: "God tells Jacob to return to Bethel. Jacob buries his household's foreign gods under an oak tree. God appears and reaffirms his name as Israel and the covenant promises. Rachel dies giving birth to Benjamin on the road to Bethlehem. Isaac dies at 180, and Esau and Jacob bury him together.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Bethel", id: "bethel" },
        { phrase: "Rachel", id: "rachel" },
        { phrase: "Benjamin", id: "benjamin" },
        { phrase: "Isaac", id: "isaac" },
      ],
    },
    {
      chapter: 36,
      title: "Esau's Descendants",
      summary: "A genealogy of Esau's descendants — the Edomites — who settle in the hill country of Seir. The chapter lists his wives, sons, chieftains, and the kings who ruled Edom before any king reigned in Israel. Esau and Jacob have separated permanently; their nations will interact for centuries.",
      wikiTerms: [
        { phrase: "Esau", id: "esau" },
        { phrase: "Edom", id: "edom" },
      ],
    },
    {
      chapter: 37,
      title: "Joseph's Dreams",
      summary: "Jacob loves his son Joseph more than all the others and gives him a richly ornamented coat. Joseph's brothers hate him. When Joseph tells them his dreams — sheaves of grain bowing to his, the sun, moon, and eleven stars bowing to him — they hate him even more. They seize him, throw him in a pit, and sell him to traders heading to Egypt.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Egypt", id: "egypt" },
        { phrase: "Reuben", id: "reuben" },
        { phrase: "Judah", id: "judah" },
      ],
    },
    {
      chapter: 38,
      title: "Judah and Tamar",
      summary: "The story abruptly shifts to Judah. His son Er marries Tamar, but God kills Er for wickedness. Judah refuses to give Tamar his youngest son as custom requires. Tamar disguises herself as a prostitute, sleeps with Judah himself, and becomes pregnant. When Judah learns the truth, he admits: \"She has been more righteous than I.\"",
      wikiTerms: [
        { phrase: "Judah", id: "judah" },
        { phrase: "Tamar", id: "tamar" },
      ],
    },
    {
      chapter: 39,
      title: "Joseph in Potiphar's House",
      summary: "Joseph is sold to Potiphar, an officer of Pharaoh. Everything Joseph touches prospers, and he's put in charge of the entire household. Potiphar's wife tries daily to seduce him. He refuses. She grabs his garment; he runs, leaving it behind. She accuses him of assault. Joseph is thrown into prison.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Potiphar", id: "potiphar" },
        { phrase: "Pharaoh", id: "pharaoh" },
      ],
    },
    {
      chapter: 40,
      title: "Dreams in Prison",
      summary: "In prison, Joseph meets Pharaoh's cupbearer and baker, both troubled by dreams. Joseph interprets them: the cupbearer will be restored to his position in three days; the baker will be executed. Both predictions come true exactly. Joseph asks the cupbearer to remember him — but the cupbearer forgets.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Pharaoh", id: "pharaoh" },
      ],
    },
    {
      chapter: 41,
      title: "Pharaoh's Dreams",
      summary: "Two years later, Pharaoh has disturbing dreams: seven fat cows devoured by seven thin cows, seven plump ears of grain swallowed by seven withered ones. No one can interpret them. The cupbearer finally remembers Joseph. Joseph tells Pharaoh: seven years of abundance will be followed by seven years of devastating famine. Pharaoh makes Joseph second in command over all Egypt.",
      wikiTerms: [
        { phrase: "Pharaoh", id: "pharaoh" },
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Egypt", id: "egypt" },
        { phrase: "famine", id: "the-famine" },
      ],
    },
    {
      chapter: 42,
      title: "The Brothers Come to Egypt",
      summary: "The famine reaches Canaan. Jacob sends ten of his sons to buy grain in Egypt — but keeps Benjamin, his youngest, home. The brothers bow before Joseph without recognizing him. Joseph accuses them of being spies and imprisons Simeon, demanding they return with Benjamin to prove their story. They're guilt-stricken, convinced this is punishment for what they did to Joseph years ago.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Benjamin", id: "benjamin" },
        { phrase: "Simeon", id: "simeon" },
        { phrase: "Egypt", id: "egypt" },
      ],
    },
    {
      chapter: 43,
      title: "The Second Journey",
      summary: "The grain runs out. Jacob reluctantly allows Benjamin to go to Egypt. Judah pledges his own life as guarantee. The brothers arrive and are invited to dine at Joseph's house — bewildering them. Joseph sees Benjamin and is so overcome he slips away to weep privately. He seats them in birth order, which astonishes them, and gives Benjamin five times more food than the others.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Benjamin", id: "benjamin" },
        { phrase: "Judah", id: "judah" },
        { phrase: "Joseph", id: "joseph-genesis" },
      ],
    },
    {
      chapter: 44,
      title: "The Silver Cup",
      summary: "Joseph plants his silver cup in Benjamin's sack. When it's discovered, the brothers are dragged back in despair. Judah steps forward and delivers one of the most powerful speeches in Genesis: he describes their father's grief, his pledge to protect Benjamin, and begs to take Benjamin's place as a slave.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Benjamin", id: "benjamin" },
        { phrase: "Judah", id: "judah" },
      ],
    },
    {
      chapter: 45,
      title: "Joseph Reveals Himself",
      summary: "Unable to contain himself any longer, Joseph clears the room and weeps so loudly the Egyptians hear it. \"I am Joseph,\" he says. \"Is my father still alive?\" His brothers are terrified. But Joseph tells them not to be angry with themselves — God sent him ahead to preserve life. He sends them home with wagons to bring the whole family to Egypt.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Egypt", id: "egypt" },
      ],
    },
    {
      chapter: 46,
      title: "Jacob Moves to Egypt",
      summary: "Jacob sets out for Egypt with everything he has. At Beersheba, God speaks to him in a vision: \"Do not be afraid to go down to Egypt, for I will make you a great nation there.\" The chapter lists all seventy members of Jacob's family who enter Egypt. Joseph rides out to meet his father, and they weep on each other's necks for a long time.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Beersheba", id: "beersheba" },
        { phrase: "Egypt", id: "egypt" },
      ],
    },
    {
      chapter: 47,
      title: "The Family in Egypt",
      summary: "Joseph presents his family to Pharaoh. Jacob, at 130, blesses Pharaoh. Joseph settles his family in the best land — Goshen. As the famine worsens, Joseph collects all of Egypt's money, livestock, and land in exchange for grain, consolidating Pharaoh's power. Jacob lives in Egypt for seventeen years and asks Joseph to swear he'll bury him in Canaan.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Pharaoh", id: "pharaoh" },
        { phrase: "Goshen", id: "goshen" },
      ],
    },
    {
      chapter: 48,
      title: "Blessing Ephraim and Manasseh",
      summary: "Jacob, near death, adopts Joseph's two sons Ephraim and Manasseh as his own — giving them equal standing with his other sons. When Joseph positions them for the blessing with the firstborn Manasseh at Jacob's right hand, Jacob deliberately crosses his arms, placing his right hand on the younger Ephraim. Joseph objects, but Jacob insists: the younger will be greater.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Ephraim", id: "ephraim" },
        { phrase: "Manasseh", id: "manasseh" },
      ],
    },
    {
      chapter: 49,
      title: "Jacob Blesses His Sons",
      summary: "Jacob gathers all twelve sons for his final words — part blessing, part prophecy, part reckoning. Reuben loses his preeminence. Simeon and Levi are scattered for their violence. Judah is promised the scepter — kings will come from his line. Joseph receives the richest blessing. Each son's destiny shapes a future tribe of Israel. Jacob dies.",
      wikiTerms: [
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Reuben", id: "reuben" },
        { phrase: "Judah", id: "judah" },
        { phrase: "Joseph", id: "joseph-genesis" },
      ],
    },
    {
      chapter: 50,
      title: "Burial and Forgiveness",
      summary: "Joseph weeps over his father's body. Jacob is embalmed Egyptian-style and carried in a great procession back to Canaan, where he is buried at Machpelah. The brothers, terrified that Joseph will now take revenge, beg for forgiveness. Joseph weeps and speaks one of the Bible's defining lines: \"You meant evil against me, but God meant it for good.\" Joseph dies at 110.",
      wikiTerms: [
        { phrase: "Joseph", id: "joseph-genesis" },
        { phrase: "Jacob", id: "jacob" },
        { phrase: "Machpelah", id: "machpelah" },
        { phrase: "Canaan", id: "canaan" },
      ],
    },
  ],
});
